"""街道空间评分因素权重分析：修改 JAVASCRIPT 后运行，即更新网站和发布包。"""
JAVASCRIPT = r'''/* Stable light-theme charts. All calculated values come from the shared point-ID dataset. */
'use strict';
const D=window.INCLUSIVE, PAGE=document.body.dataset.page;
const W=document.querySelector('.workspace'),NAV=document.querySelector('.tabs'),NOTE=document.querySelector('.readme');
const FONT='Times New Roman, SimSun, Songti SC, serif', INK='#292929', PALETTE=['#607E95','#A8C3D6','#B8AEA6','#E2D0BC','#F3EEE8','#D59BA8','#A45668'];
let charts=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const finite=Number.isFinite, fmt=(v,n=3)=>finite(v)?v.toFixed(n):'—';
const sum=a=>a.reduce((s,v)=>s+(finite(v)?v:0),0),mean=a=>{a=a.filter(finite);return a.length?sum(a)/a.length:null;};
const stars=p=>!finite(p)?'':p<.001?'***':p<.01?'**':p<.05?'*':'';
const SFORM=`标准化值 z=(x−全域最小值)/(全域最大值−全域最小值)，常量指标记0。\n停留密度=行人样本数/有效停留空间面积。\n集聚比例=集聚人数/行人样本数。\n原始活力度 V₀=(z人数+z行为集群数+z停留密度+z集聚比例)/4；任一指标缺失则不评分。\n展示活力度 V=min(1,c×V₀)，当前 c=${D.vitalityCoefficient.toFixed(4)}。\nc取覆盖0–1所需系数与至少8个双高节点所需系数的较大值；这是展示校准，不是新增观测。`;
const MFORM='第 d 维混合度 H_d=−Σ(p_k×ln p_k)/ln K_d，p_k=该类别频数/该维频数合计，0×ln0记0。\n五维类别数依次为：年龄混合度4、活动丰富度14、身份倾向混合度2、姿态丰富度2、社交状态混合度2。\n混合度综合评分 M=(H年龄+H活动+H身份倾向+H姿态+H社交状态)/5；任一维缺失则不评分。\n居民指数>游客指数记居民倾向，反之记游客倾向，相等或缺失不计入身份维；活动可多选。';
document.querySelector('.meta').textContent=`2026人因空间·${['composition','memory','diversity'].includes(PAGE)?D.recordCount:D.rows}RECORDS`;
function el(tag,cls,parent=W){const n=document.createElement(tag);if(cls)n.className=cls;parent.append(n);return n;}
function reset(){charts.forEach(c=>c.dispose());charts=[];W.replaceChildren();document.querySelector('.map-tooltip')?.remove();}
function tabs(parent,labels,render){parent.replaceChildren();labels.forEach((s,i)=>{const b=el('button','',parent);b.textContent=s;b.setAttribute('role','tab');b.onclick=()=>{parent.querySelectorAll('button').forEach(v=>v.setAttribute('aria-selected',String(v===b)));render(i);};if(!i)b.click();});}
function mainTabs(labels,render){tabs(NAV,labels,i=>{reset();render(i);});}
function note(text){NOTE.textContent=text;}
function chart(parent=W,height=520){const n=el('div','plot',parent);n.style.height=height+'px';const c=echarts.init(n,null,{renderer:'canvas'});charts.push(c);return c;}
function base(){return {animation:false,backgroundColor:'#fff',color:PALETTE,textStyle:{color:INK,fontFamily:FONT},title:{textStyle:{color:INK,fontFamily:FONT,fontSize:17,fontWeight:400}},tooltip:{confine:true,backgroundColor:'#fff',borderColor:'#A8C3D6',textStyle:{color:INK,fontFamily:FONT}},grid:{left:75,right:35,top:65,bottom:90,containLabel:true},legend:{top:38,left:20,right:20,type:'scroll',textStyle:{color:'#4B4B4B',fontFamily:FONT}},xAxis:axis(),yAxis:axis()};}
function axis(name=''){return {type:'value',name,nameLocation:'middle',nameGap:40,nameTextStyle:{color:'#4B4B4B',fontFamily:FONT},axisLabel:{color:'#4B4B4B',fontFamily:FONT},axisLine:{show:true,lineStyle:{color:'#A8C3D6'}},splitLine:{lineStyle:{color:'#B8AEA6'}}};}
function regression(a){if(a.length<2)return null;const mx=mean(a.map(p=>p[0])),my=mean(a.map(p=>p[1]));let xx=0,xy=0,yy=0;a.forEach(([x,y])=>{xx+=(x-mx)**2;xy+=(x-mx)*(y-my);yy+=(y-my)**2;});if(!xx)return null;return {b:xy/xx,a:my-xy/xx*mx,r2:yy?xy*xy/xx/yy:null,n:a.length,min:Math.min(...a.map(p=>p[0])),max:Math.max(...a.map(p=>p[0]))};}
function highlight(road){charts.forEach(c=>(c.getOption().series||[]).forEach((s,i)=>c.dispatchAction({type:s.name===road?'highlight':'downplay',seriesIndex:i})));}
function scatter(parent,xkey,ykey,title){const c=chart(parent),o=base(),series=[],all=[];delete o.legend;o.title={text:title,left:'center',textStyle:{fontFamily:FONT,fontSize:16,color:INK}};o.xAxis=axis(D.headers[xkey]);o.yAxis=axis(D.headers[ykey]);
 [...new Set(D.points.map(p=>p.road))].forEach(road=>{const data=D.points.filter(p=>p.road===road&&finite(p.values[xkey])&&finite(p.values[ykey])).map(p=>[p.values[xkey],p.values[ykey],p.address]);all.push(...data);if(data.length)series.push({name:road,type:'scatter',data,symbolSize:8,itemStyle:{color:'#A8C3D6',opacity:1},emphasis:{itemStyle:{color:'#292929'},scale:1.4}});});
 const f=regression(all);if(f){series.push({name:'回归线',type:'line',data:[[f.min,f.a+f.b*f.min],[f.max,f.a+f.b*f.max]],symbol:'none',silent:true,lineStyle:{color:'#292929',opacity:.18,type:f.r2>=.5?'solid':'dashed'}});o.graphic=[{type:'text',right:18,bottom:8,style:{text:`y=${fmt(f.b)}x+${fmt(f.a)}\nR²=${fmt(f.r2)} · n=${f.n}`,fill:'#4B4B4B',font:'12px SimSun',lineHeight:17,textAlign:'right'}}];}
 o.series=series;o.tooltip.formatter=p=>p.seriesType==='scatter'?`${esc(p.data[2])}<br>${esc(D.headers[xkey])}：${fmt(p.data[0])}<br>${esc(D.headers[ykey])}：${fmt(p.data[1])}`:'';c.setOption(o);c.on('mouseover',p=>{if(p.seriesType==='scatter')highlight(p.seriesName)});c.on('globalout',()=>highlight(null));}

function mapView(mode){note(mode===0?'选择活动查看原点位人数；圈越大人数越多，悬停时同一道路同时变实。\n圆半径 r=3+22×√(该点人数/当前指标最大人数)；按底图宽高的百分比定位。\n活动人数读取总表对应人数列；缺失观测仅在此地图按0显示。':'灰色表示人数少，橙色表示人数多；色块叠加展示人群在底图上的集中区域。\n权重 w=该点行人样本数/全域最大行人样本数。\n热度 h(x,y)=Σ[w_i×exp(−距离²/(2×σ²))]，σ=底图宽度的1.8%；热度按全图最大值归一化，缺失人数仅在此地图按0处理。');
 const tools=el('div','map-tools');let selected='AU';const pick=el('select','',tools);['AU','AV','AX','AY','BA','BB'].forEach(k=>{const option=el('option','',pick);option.value=k;option.textContent=D.headers[k]});if(mode===1)pick.hidden=true;
 const stage=el('div','map-stage'),img=el('img','',stage);img.src='../assets/data/map.jpg';img.alt='衡复风貌区调研底图';
 const NS='http://www.w3.org/2000/svg',svg=document.createElementNS(NS,'svg');svg.setAttribute('viewBox','0 0 1000 706.38');svg.setAttribute('role','img');svg.setAttribute('aria-label',mode?'行人样本数热力分布':'活动样本数地图');stage.append(svg);
 const tip=el('div','map-tooltip',document.body);tip.hidden=true;
 function hover(ev,p,key){tip.innerHTML=esc(p.address)+'<br>'+esc(D.headers[key])+'：'+fmt(p.values[key]??0,0);tip.hidden=false;tip.style.left=Math.min(ev.clientX+12,window.innerWidth-280)+'px';tip.style.top=Math.max(10,Math.min(ev.clientY+12,window.innerHeight-100))+'px';}
 function draw(){svg.replaceChildren();const key=mode?'AH':selected,max=Math.max(1,...D.points.map(p=>p.values[key]||0));
  if(mode){const canvas=document.createElement('canvas');canvas.width=700;canvas.height=495;const ctx=canvas.getContext('2d'),values=new Float32Array(700*495);let peak=0;const sigma=12.6;
   D.points.forEach(p=>{if(!p.position)return;const weight=Math.max(0,p.values.AH||0)/max,cx=p.position.x_percent*7,cy=p.position.y_percent*4.95;if(!weight)return;for(let y=Math.max(0,Math.floor(cy-3*sigma));y<Math.min(495,cy+3*sigma);y++)for(let x=Math.max(0,Math.floor(cx-3*sigma));x<Math.min(700,cx+3*sigma);x++){const v=values[y*700+x]+=weight*Math.exp(-((x-cx)**2+(y-cy)**2)/(2*sigma*sigma));peak=Math.max(peak,v);}});
   const pixels=ctx.createImageData(700,495),colors=[[164,166,167],[182,175,167],[198,184,167],[225,182,130],[252,180,94]];
   values.forEach((v,i)=>{if(!v)return;const t=v/peak,f=t*4,j=Math.min(3,Math.floor(f));for(let k=0;k<3;k++)pixels.data[i*4+k]=colors[j][k]*(1-(f-j))+colors[j+1][k]*(f-j);pixels.data[i*4+3]=255*Math.min(.82,t*5);});ctx.putImageData(pixels,0,0);const image=document.createElementNS(NS,'image');image.setAttribute('href',canvas.toDataURL());image.setAttribute('width','1000');image.setAttribute('height','706.38');svg.append(image);
  }
  D.points.forEach(p=>{if(!p.position)return;const n=p.values[key]||0,g=document.createElementNS(NS,'g');g.classList.add('map-point');g.dataset.road=p.road;g.setAttribute('tabindex','0');g.setAttribute('aria-label',p.address+' '+n+'人');g.setAttribute('transform',`translate(${p.position.x_percent*10},${p.position.y_percent*7.0638})`);
   const radius=mode?4:3+22*Math.sqrt(n/max);(mode?[1]:[1,.76,.5]).forEach((scale,i)=>{const c=document.createElementNS(NS,'circle');c.setAttribute('r',radius*scale);c.setAttribute('fill',mode?'#292929':'#A45668');c.setAttribute('fill-opacity',mode?'.04':n===0?'.04':String(.12+i*.08));c.setAttribute('stroke','#292929');c.setAttribute('stroke-opacity',mode?'0':'.13');g.append(c)});
   const activate=e=>{svg.querySelectorAll('.map-point').forEach(v=>v.classList.toggle('active',v.dataset.road===p.road));if(e.clientX!==undefined)hover(e,p,key);};g.addEventListener('pointerenter',activate);g.addEventListener('pointermove',e=>hover(e,p,key));g.addEventListener('focus',activate);const clear=()=>{svg.querySelectorAll('.active').forEach(v=>v.classList.remove('active'));tip.hidden=true};g.addEventListener('pointerleave',clear);g.addEventListener('blur',clear);svg.append(g);
  });
 }
 pick.onchange=()=>{selected=pick.value;draw()};draw();if(mode){const legend=el('div','heat-legend');legend.innerHTML='低人数 <span class="heat-gradient"></span> 高人数';}
}

function weights(){note('每行代表一条道路，六段长度表示各项评分均值；悬停查看评分及所占比例。\n道路某项均值=该道路有效评分之和/有效点位数。\n遮荫评分=遮荫率(%)/20。\n六项合计=开放度+互动性+视觉丰富度+历史感知度+遮荫评分+路面状态，满分30。\n某项构成比例=该项均值/六项均值合计×100%。');const c=chart(W,Math.max(650,D.weights.length*29+120)),o=base(),names=['界面开放度','临街互动性','视觉丰富度','历史感知度','遮荫率','路面状态'];o.grid={left:100,right:30,top:70,bottom:35};o.xAxis=axis();o.yAxis={type:'category',data:D.weights.map(g=>g.road),axisLabel:{fontFamily:FONT,interval:0},inverse:true};o.series=names.map((name,j)=>({name,type:'bar',stack:'total',data:D.weights.map(g=>g.values[j]),itemStyle:{color:['#292929','#4B4B4B','#A8C3D6','#B8AEA6','#A45668','#A8C3D6'][j],opacity:j===5?.55:1},label:{show:true,color:j<2?'#fff':'#292929',formatter:p=>fmt(p.value,1)}}));o.tooltip.trigger='axis';o.tooltip.formatter=ps=>esc(ps[0].name)+'<br>'+ps.map(p=>`${esc(p.seriesName)}：${fmt(p.value,2)} (${fmt(p.value/sum(ps.map(v=>v.value))*100,1)}%)`).join('<br>');c.setOption(o);}
function composition(i){const age=i!==2,key=age?'ages':'identities',labels=age?['幼年','青年','中年','老年']:['居民倾向','游客倾向'];let groups=i===1?D.points.filter(p=>p.n).slice().sort((a,b)=>b.ages[3]/sum(b.ages)-a.ages[3]/sum(a.ages)):[D.all,...D.admins.slice().sort((a,b)=>b[key][age?1:0]/sum(b[key])-a[key][age?1:0]/sum(a[key]))];note('每行总长为该群体的有效构成，悬停查看人数；点位年龄构成按老年比例排序。\n类别比例=该类人数/该维有效人数×100%。\n居民指数>游客指数记居民倾向，反之记游客倾向；相等或缺失不计入身份构成。');const c=chart(W,Math.max(490,groups.length*28+120)),o=base();o.grid={left:i===1?240:140,right:35,top:70,bottom:40};o.xAxis={...axis('构成（%）'),max:100};o.yAxis={type:'category',data:groups.map(g=>g.name+' · n='+g.n),inverse:true,axisLabel:{interval:0,fontSize:11,fontFamily:FONT}};o.series=labels.map((name,j)=>({name,type:'bar',stack:'share',data:groups.map(g=>sum(g[key])?g[key][j]/sum(g[key])*100:null),itemStyle:{color:['#292929','#A8C3D6','#B8AEA6','#A45668'][j],opacity:!age&&j===1?.35:1},label:{show:true,color:j===0?'#fff':'#292929',formatter:p=>p.value>=8?fmt(p.value,1)+'%':''}}));o.tooltip.trigger='axis';c.setOption(o);}
function memory(i){note('连线宽度表示该年龄群体的观测条数；左侧是活动推演的原初功能，右侧是点位当前功能。\n映射按饮食→餐饮/饮品、光顾→零售、工作→生产/办公、打卡→文化展示优先匹配，其余归为生活服务。\n每条记录只进入一个映射，连线人数=对应映射的记录条数。\n这是代际偏好假设，非历史用途实测，也不把年龄层直接换算为具体年份。');const g=D.memory[i],c=chart(W,Math.max(550,Math.min(850,window.innerHeight*.8))),o=base();delete o.xAxis;delete o.yAxis;delete o.grid;delete o.legend;const left=[...new Set(g.links.map(v=>v.source))],right=[...new Set(g.links.map(v=>v.target))];
 const layout=()=>{const narrow=c.getWidth()<650;return {series:[{type:'sankey',left:narrow?8:'19%',right:narrow?8:'23%',top:35,bottom:25,nodeWidth:12,nodeGap:16,draggable:false,data:[...left.map(name=>({name:'假设：'+name,depth:0})),...right.map(name=>({name:'当前：'+name,depth:1}))],links:g.links.map(v=>({source:'假设：'+v.source,target:'当前：'+v.target,value:v.value})),itemStyle:{color:'#292929',borderWidth:0},lineStyle:{color:'#292929',opacity:.16},label:{color:'#292929',fontFamily:FONT,fontSize:narrow?10:12,width:narrow?120:180,overflow:'break',formatter:p=>p.name.replace(/^(假设：|当前：)/,'')},levels:[{depth:0,label:{position:narrow?'right':'left'}},{depth:1,label:{position:narrow?'left':'right'}}],emphasis:{focus:'adjacency',lineStyle:{opacity:.5}}}]};};o.tooltip.formatter=p=>p.dataType==='edge'?`${esc(p.data.source)} → ${esc(p.data.target)}<br>${p.data.value}条观测`:esc(p.name);c.setOption({...o,...layout()});c.reflow=()=>c.setOption(layout());}
function space(i){note('每个点代表一个节点，悬停同步突出同一道路；灰色短线为各道路回归，悬停同路点位时一起高亮；整体回归为深粉色实线（R²≥0.5）或浅粉色虚线（R²<0.5），道路回归也按同一标准区分实虚线；有效点少于3或横轴恒定不拟合。右下角显示回归方程、R²和有效点位数。\n斜率 b=Σ[(x−x̄)(y−ȳ)]/Σ(x−x̄)²。\n截距 a=ȳ−b×x̄，预测值 ŷ=a+bx。\nR²=1−Σ(y−ŷ)²/Σ(y−ȳ)²；分母为0时不定义，缺失值逐对排除。\n节点空间长度、有效面积、承载人数、消费空间占比及各舒适度指标直接采用总表记录。');if(i===0){const sub=el('div','subtabs'),host=el('div','single-space-chart');const options=[['M','空间有效性分析'],['S','空间承载力分析'],['R','消费空间占比分析']];tabs(sub,options.map(v=>v[1]),j=>{charts.forEach(c=>c.dispose());charts=[];host.replaceChildren();scatter(host,'K',options[j][0],options[j][1]);});}else{const grid=el('div','chart-grid');[['AE','遮荫率'],['AF','声环境舒适度'],['AG','气味环境']].forEach(([y,t])=>scatter(grid,'T',y,t));}}

function radar(parent,groups,title,height=530){const c=chart(parent,height),o=base();delete o.xAxis;delete o.yAxis;delete o.grid;const dims=['年龄混合度','活动丰富度','身份倾向混合度','姿态丰富度','社交状态混合度'];o.title={text:title,left:'center',top:0,textStyle:{fontSize:16,fontFamily:FONT}};o.legend.top=30;o.radar={center:['50%','57%'],radius:'59%',indicator:dims.map(name=>({name,max:1})),axisName:{color:'#292929',fontFamily:FONT},splitArea:{show:false},axisLine:{lineStyle:{color:'#B8AEA6'}},splitLine:{lineStyle:{color:'#B8AEA6'}}};o.series=groups.filter(g=>g.mix.every(finite)).map((g,j)=>({name:g.name,type:'radar',symbol:['circle','rect','triangle','diamond'][j%4],symbolSize:5,lineStyle:{color:PALETTE[j%7],opacity:j?.7:1,type:j?'solid':'dashed',width:j?1:2},itemStyle:{color:PALETTE[j%7]},data:[{name:g.name,value:g.mix}],emphasis:{lineStyle:{width:3,opacity:1}}}));o.tooltip.formatter=p=>esc(p.name)+'<br>'+dims.map((v,j)=>v+'：'+fmt(p.value[j])).join('<br>');c.setOption(o);return c;}
function scorePlot(parent,points,key,title){const compact=key==='mixScore',valid=points.filter(p=>finite(p[key])),container=el('div',compact?'score-wrap score-fit':'score-wrap',parent),c=chart(container,480),o=base();delete o.legend;o.title={text:title,left:'center',textStyle:{fontFamily:FONT,fontSize:16}};o.grid={left:60,right:24,top:80,bottom:compact?45:120,containLabel:true};o.xAxis={...axis(),type:'category',data:valid.map(p=>p.name),axisTick:{show:!compact},axisLabel:{show:!compact,rotate:45,interval:0,fontSize:10,fontFamily:FONT}};o.yAxis={...axis('综合评分'),min:0,max:1};o.series=[{type:'scatter',symbolSize:7,data:valid.map(p=>p[key]),itemStyle:{color:'#4B4B4B',opacity:1},label:{show:true,position:'top',color:'#292929',fontFamily:FONT,fontSize:10,formatter:p=>fmt(p.value,2)}}];o.tooltip.formatter=p=>esc(valid[p.dataIndex].address)+'<br>评分：'+fmt(p.value)+'<br>行人样本 n='+valid[p.dataIndex].n;c.setOption(o);return c;}
function lorenz(parent,g){const c=chart(parent,480),o=base(),order=g.actions.map((v,j)=>({v,j})).sort((a,b)=>a.v-b.v||a.j-b.j);o.title={text:'行为集中度：洛伦兹曲线',left:'center',top:5,textStyle:{fontFamily:FONT,fontSize:16}};o.legend={...o.legend,top:40,left:10,right:10};o.grid={left:55,right:20,top:92,bottom:115,containLabel:true};o.xAxis={...axis(),type:'category',data:['起点',...order.map(p=>D.behaviorLabels[p.j])],axisLabel:{rotate:55,interval:0,fontSize:10,fontFamily:FONT}};o.yAxis={...axis('行为出现次数累计比例'),min:0,max:1};o.series=[{name:'均等线',type:'line',data:Array.from({length:15},(_,i)=>i/14),symbol:'none',lineStyle:{color:'#A8C3D6',type:'dashed'}},{name:g.name,type:'line',data:g.lorenz||[],symbolSize:4,lineStyle:{color:'#292929'},itemStyle:{color:'#292929'}}];o.tooltip.trigger='axis';c.setOption(o);}
function diversity(i){note('五边形越外扩，群体在相应维度越多样；点击行政街道内的道路，向下查看该道路及点位、行为曲线和综合评分。小样本点位仍显示，但 n<5 的结果容易波动。\n'+MFORM+'\n洛伦兹纵坐标 L_j=前j类行为频数累计/14类行为频数合计，行为按频数从低到高排序。');const groups=i===0?[D.all,...D.admins]:[D.admins[i-1],...D.admins[i-1].roads];const c=radar(W,groups,i===0?'全域与所有街道':D.admins[i-1].name);if(!i)return;const admin=D.admins[i-1],buttons=el('div','road-buttons'),drill=el('section','drill');
 function open(road){while(charts.length>1){charts.pop().dispose()}drill.replaceChildren();el('h2','section-heading',drill).textContent=road+' · 道路与节点';const group=admin.roads.find(g=>g.name===road),pts=D.points.filter(p=>p.admin===admin.name&&p.road===road&&p.n);const grid=el('div','chart-grid',drill),a=el('div','',grid),b=el('div','',grid),d=el('div','',grid);radar(a,[group,...pts],road+'及各点位',480);lorenz(b,group);scorePlot(d,pts,'mixScore','点位混合度综合评分');el('p','caption',drill).textContent='点位标注为地址，悬停可查看样本量。\n'+MFORM;drill.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});}
 admin.roads.forEach(g=>{const b=el('button','',buttons);b.textContent=g.name;b.onclick=()=>open(g.name)});c.on('legendselectchanged',p=>{if(admin.roads.some(g=>g.name===p.name)){c.dispatchAction({type:'legendSelect',name:p.name});open(p.name)}});c.on('click',p=>{if(admin.roads.some(g=>g.name===p.name))open(p.name)});
}

function correlations(i){if(i===1){note('每个点显示一个节点的活力度评分，点上方标出分数；分数越高，当前观测下的活动强度越高。缺少评分输入的点位列在图后。\n'+SFORM);scorePlot(W,D.points,'vitality','活力度综合评分');missingScores('vitality');return;}
 note('圆越大，关联越强；实心表示正相关，空心表示负相关；数值下方显示星号显著性，—表示数据不足或指标不变化。\nρ=Σ[(R_x−R̄_x)(R_y−R̄_y)]/√[Σ(R_x−R̄_x)²×Σ(R_y−R̄_y)²]，并列值采用平均秩，逐对排除缺失。\nA、B1、B2、B3、C、D按具体类别展开：某类别出现=1，未出现=0；整项未记录保留缺失。\n'+SFORM+'\n年龄混合度 H=−Σ(p_k ln p_k)/ln4。\n居民/游客指数=该点位行人表相应指数的有效值均值。\n* p<0.05，** p<0.01，*** p<0.001；p为双侧Spearman近似检验，未做多重检验校正。');
 const ys=Object.keys(D.ys),wrap=el('div','table-scroll');let html='<table><thead><tr><th>空间指标 / 行人指标</th>'+ys.map(k=>'<th>'+esc(D.ys[k])+'</th>').join('')+'</tr></thead><tbody>';
 D.fields.forEach(f=>{html+='<tr><th>'+esc(f.label)+'</th>'+ys.map(y=>{const r=D.correlations.find(r=>r.x===f.key&&r.y===y);if(!finite(r.rho))return '<td title="有效配对 '+r.n+'">—</td>';const size=32+36*Math.sqrt(Math.abs(r.rho));return `<td class="circle-cell" title="n=${r.n}; p=${r.p}"><span class="circle ${r.rho<0?'negative':'positive'}" style="width:${size}px;height:${size}px;--alpha:${.5+.5*Math.abs(r.rho)}">${fmt(r.rho)}${stars(r.p)}</span></td>`}).join('')+'</tr>';});wrap.innerHTML=html+'</tbody></table>';
 const heading=el('h2','section-heading');heading.textContent='Spearman相关系数';const table=el('div','table-scroll');table.innerHTML='<table><thead><tr><th>空间指标 / 行人指标</th>'+ys.map(k=>'<th>'+esc(D.ys[k])+'</th>').join('')+'</tr></thead><tbody>'+D.fields.map(f=>'<tr><th>'+esc(f.label)+'</th>'+ys.map(y=>{const r=D.correlations.find(r=>r.x===f.key&&r.y===y);return '<td>'+fmt(r.rho)+stars(r.p)+'</td>'}).join('')+'</tr>').join('')+'</tbody></table>';
}
function missingScores(key){const pts=D.points.filter(p=>!finite(p[key]));if(pts.length){const p=el('p','notice');p.textContent=`${pts.length} 个点位缺少评分输入，未将缺失填为0：`+pts.map(p=>p.name).join('、');}}
function mismatch(i){if(!i){note('横轴活力度、纵轴混合度，越右越活跃、越上越多样；虚线以0.5划分高低，悬停查看节点。缺少任一评分的点位不绘制。\n'+SFORM+'\n'+MFORM+'\n高活力低混合：V≥0.5且M<0.5；双高：V≥0.5且M≥0.5。');const c=chart(W,600),o=base();o.xAxis={...axis('活力度 V'),min:0,max:1};o.yAxis={...axis('混合度 M'),min:0,max:1};const pts=D.points.filter(p=>finite(p.vitality)&&finite(p.mixScore));o.series=[{type:'scatter',symbolSize:9,data:pts.map(p=>[p.vitality,p.mixScore,p.address,p.n]),itemStyle:{color:'#4B4B4B',opacity:1},markLine:{silent:true,symbol:'none',lineStyle:{color:'#A8C3D6',type:'dashed'},label:{show:false},data:[{xAxis:.5},{yAxis:.5}]},markArea:{silent:true,itemStyle:{color:'#00000003'},label:{color:'#4B4B4B',fontFamily:FONT},data:[[{name:'低活力高混合',xAxis:0,yAxis:.5},{xAxis:.5,yAxis:1}],[{name:'双高',xAxis:.5,yAxis:.5},{xAxis:1,yAxis:1}],[{name:'双低',xAxis:0,yAxis:0},{xAxis:.5,yAxis:.5}],[{name:'高活力低混合',xAxis:.5,yAxis:0},{xAxis:1,yAxis:.5}]]}}];o.tooltip.formatter=p=>`${esc(p.data[2])}<br>V=${fmt(p.data[0])}，M=${fmt(p.data[1])}<br>行人样本 n=${p.data[3]}`;c.setOption(o);missingScores('mismatch');return;}
 note('两个板块分别比较高活力低混合和双高点位。选择界面指标，横轴是不配得性，纵轴是所选评分；按不配得性顺序连接观测点，连线仅帮助阅读，不代表时间变化或因果。\n不配得性 U=ln[(1+V)/(1+M)]；V=M时为0，V>M为正，V<M为负。\nV、M均为0–1评分；加入1使零值可计算，双高或双低且相近时U接近0。\n遮荫评分=遮荫率(%)/20；其余界面指标使用总表评分。');const sub=el('div','subtabs'),host=el('div');const keys=['U','V','Y','Z','AE','AA'];tabs(sub,keys.map(k=>k==='AE'?'遮荫评分':D.headers[k]),idx=>{charts.forEach(c=>c.dispose());charts=[];host.replaceChildren();const grid=el('div','chart-grid two',host);['高活力低混合','双高'].forEach(group=>{const panel=el('section','',grid);el('h2','section-heading',panel).textContent=group;const key=keys[idx],pts=D.points.filter(p=>p.quadrant===group&&finite(p.values[key])).sort((a,b)=>a.mismatch-b.mismatch);if(!pts.length){el('p','empty',panel).textContent='当前没有满足条件且该指标有效的点位。';return;}const c=chart(panel,490),o=base();o.xAxis=axis('不配得性 U');o.yAxis=axis(key==='AE'?'遮荫评分':D.headers[key]);o.series=[{type:'line',data:pts.map(p=>[p.mismatch,p.values[key]/(key==='AE'?20:1),p.address]),symbolSize:8,lineStyle:{color:'#4B4B4B',opacity:.4},itemStyle:{color:'#292929'},label:{show:true,position:'top',fontFamily:FONT,fontSize:10,formatter:p=>fmt(p.data[1],1)}}];o.tooltip.formatter=p=>esc(p.data[2])+'<br>U='+fmt(p.data[0])+'<br>评分='+fmt(p.data[1]);c.setOption(o);});});}

/* Revision functions are inserted into each editable renderer before page initialization. */
const MIXLABELS=['年龄混合度','活动丰富度','身份倾向混合度','姿态丰富度','社交状态混合度'];
function fittedRegression(data){
 const a=data.filter(p=>finite(p[0])&&finite(p[1])),n=a.length;if(n<3)return null;
 const mx=a.reduce((s,p)=>s+p[0],0)/n,my=a.reduce((s,p)=>s+p[1],0)/n;
 const xx=a.reduce((s,p)=>s+(p[0]-mx)**2,0),yy=a.reduce((s,p)=>s+(p[1]-my)**2,0);if(xx<=0)return null;
 const slope=a.reduce((s,p)=>s+(p[0]-mx)*(p[1]-my),0)/xx,intercept=my-slope*mx;
 const residual=a.reduce((s,p)=>s+(p[1]-intercept-slope*p[0])**2,0),r2=yy>0?Math.max(0,Math.min(1,1-residual/yy)):null;
 const lo=Math.min(...a.map(p=>p[0])),hi=Math.max(...a.map(p=>p[0]));
 return {n,r2,slope,intercept,points:Array.from({length:61},(_,i)=>{const x=lo+(hi-lo)*i/60;return [x,intercept+slope*x,Math.sqrt(residual/(n-2)*(1/n+(x-mx)**2/xx))]})};
}
function regressionSeries(f,band=0,alwaysPink=false){if(!f)return [];
 const series=[{id:'regression',type:'line',silent:true,showSymbol:false,data:f.points.map(p=>p.slice(0,2)),lineStyle:{color:alwaysPink||f.r2>=.5?'#A45668':'#D59BA8',type:alwaysPink||f.r2>=.5?'solid':'dashed',width:2},z:3}];
 if(band>0)series.push({id:'regression-band',type:'custom',silent:true,data:[0],z:0,renderItem:(params,api)=>({type:'polygon',shape:{points:[...f.points.map(p=>api.coord([p[0],p[1]+band*p[2]])),...f.points.slice().reverse().map(p=>api.coord([p[0],p[1]-band*p[2]]))]},style:{fill:'#D59BA8',opacity:.22}})});
 return series;
}
function linkedNodeCharts(){const active=charts.slice();active.forEach(c=>{c.setOption({series:[{id:'nodes',emphasis:{scale:1.6,itemStyle:{opacity:1},label:{show:true,position:'top',formatter:p=>p.data[2],fontFamily:FONT,color:'#292929',backgroundColor:'rgba(255,255,255,.9)',padding:3}}}]});
 c.on('mouseover',p=>{if(p.seriesId!=='nodes'&&p.seriesIndex!==0)return;const id=p.data[3];active.forEach(other=>{other.dispatchAction({type:'downplay'});const nodes=other.getOption().series.find(s=>s.id==='nodes');const index=nodes.data.findIndex(v=>v[3]===id);if(index>=0)other.dispatchAction({type:'highlight',seriesId:'nodes',dataIndex:index});});});
 c.on('globalout',()=>active.forEach(other=>other.dispatchAction({type:'downplay'})));});}
function vitalityInformation(){
 const nav=el('div','subtabs'),host=el('div'),c=informationScatter(host,'vitality'),original=c.getOption();host.querySelector('.caption').textContent='颜色区分指标；悬停显示原始数值及点位名称。校准展示以点大小编码该指标的相对大小，散点图以各自独立纵轴编码原始数值。';
 const keys=['sample','clusters','density','gather','resident','visitor'],labels=[...keys.map(k=>D.ys[k]),'综合评分'],values=keys.map(k=>D.points.map(p=>p.metrics[k]));values.push(D.points.map(p=>p.vitality));let mode=0;
 c.off('mouseover');c.off('globalout');
 tabs(nav,['校准展示','散点图'],i=>{mode=i;const compact=window.innerWidth<700,step=compact?24:42;
 const axes=i?labels.map((name,j)=>({id:'metric-'+j,type:'value',min:'dataMin',max:'dataMax',position:j<4?'left':'right',offset:(j<4?j:j-4)*step,name:String(j+1),nameLocation:'end',nameTextStyle:{color:PALETTE[j],fontFamily:FONT},axisLine:{show:true,lineStyle:{color:PALETTE[j]}},axisLabel:{fontSize:compact?8:10,color:'#4B4B4B',formatter:v=>Number(v.toPrecision(3)).toString()},splitLine:{show:false}})):original.yAxis;
 const series=labels.map((name,j)=>({id:'info-'+j,type:'scatter',name,yAxisIndex:i?j:0,data:values[j].map((v,k)=>({id:String(D.points[k].id),value:[k,i?v:j,v]})),symbolSize:i?(v=>finite(v[2])?(j===6?10:7):0):original.series[j].symbolSize,itemStyle:{color:PALETTE[j],opacity:.5},emphasis:{scale:1.5,itemStyle:{opacity:1}}}));
 series.push({id:'focus-ring',type:'scatter',yAxisIndex:i?6:0,data:[]});
 c.setOption({animation:true,animationDurationUpdate:850,animationEasingUpdate:'cubicInOut',grid:{left:i?step*3+40:150,right:i?step*2+40:25,top:40,bottom:50},yAxis:axes,series}, {replaceMerge:'yAxis'});
 note((i?'七组散点叠加，各指标使用独立纵轴，轴号1–7依次对应：'+labels.join('、')+'。每组纵轴均从小到大，不能直接比较不同指标的绝对高度。':'每列代表一个节点，每行代表一个指标，圆点大小显示该行相对大小。')+'\n悬停联动同点位，综合评分加外圈；切换视图时点位平滑移动。\n'+SFORM);
 });
 c.on('mouseover',p=>{if(p.seriesIndex>=7)return;const i=p.data.value?p.data.value[0]:p.data[0];c.dispatchAction({type:'downplay'});labels.forEach((_,j)=>c.dispatchAction({type:'highlight',seriesIndex:j,dataIndex:i}));c.setOption({series:[{id:'focus-ring',data:finite(values[6][i])?[[i,mode?values[6][i]:6]]:[]}]});});
 c.on('globalout',()=>{c.dispatchAction({type:'downplay'});c.setOption({series:[{id:'focus-ring',data:[]}]});});
 c.setOption({tooltip:{formatter:p=>{const i=(p.data.value||p.data)[0];return esc(D.points[i].address)+'<br>'+labels.map((name,j)=>esc(name)+'：'+fmt(values[j][i])).join('<br>')}}});
}
function informationScatter(parent,kind){
 const mix=kind==='mix',keys=mix?['ageMix','activityMix','identityMix','postureMix','socialMix']:['sample','clusters','density','gather','resident','visitor'],labels=[...keys.map(k=>D.ys[k]),'综合评分'];
 const c=chart(parent,Math.max(440,Math.min(650,window.innerHeight*.68))),o=base();delete o.legend;
 o.grid={left:150,right:25,top:25,bottom:50};o.xAxis={type:'category',data:D.points.map(p=>p.name),axisLabel:{show:false},axisTick:{show:false},name:'所有点位（按总表顺序）',nameLocation:'middle',nameGap:28};
 o.yAxis={type:'category',data:labels,inverse:true,axisLabel:{color:'#4B4B4B',fontFamily:FONT,fontSize:12,interval:0},axisTick:{show:false},splitLine:{show:true,lineStyle:{color:'#F3EEE8'}}};
 const values=keys.map(k=>D.points.map(p=>p.metrics[k]));values.push(D.points.map(p=>p[mix?'mixScore':'vitality']));
 const ranges=values.map(a=>{const v=a.filter(finite);return [Math.min(...v),Math.max(...v)]});
 o.series=labels.map((name,j)=>({id:'info-'+j,name,type:'scatter',data:values[j].map((v,i)=>[i,j,v]),symbolSize:v=>{if(!finite(v[2]))return 0;const [lo,hi]=ranges[j];return 5+9*Math.sqrt(hi>lo?(v[2]-lo)/(hi-lo):.5)},itemStyle:{color:PALETTE[j%7],opacity:.5},emphasis:{scale:1.5,itemStyle:{opacity:1}},blur:{itemStyle:{opacity:.5}}}));
 o.series.push({id:'focus-ring',type:'scatter',silent:true,data:[],symbolSize:27,itemStyle:{color:'transparent',borderColor:PALETTE[6],borderWidth:2,opacity:1},z:10});
 o.tooltip.formatter=p=>{const i=p.data[0],node=D.points[i];return esc(node.address)+'<br>'+labels.map((name,j)=>esc(name)+'：'+fmt(values[j][i])).join('<br>')};c.setOption(o);
 c.on('mouseover',p=>{if(p.seriesIndex>=labels.length)return;const i=p.data[0];c.dispatchAction({type:'downplay'});labels.forEach((_,j)=>c.dispatchAction({type:'highlight',seriesIndex:j,dataIndex:i}));c.setOption({series:[{id:'focus-ring',data:finite(values.at(-1)[i])?[[i,labels.length-1]]:[]}]});});
 c.on('globalout',()=>{c.dispatchAction({type:'downplay'});c.setOption({series:[{id:'focus-ring',data:[]}]});});
 el('p','caption',parent).textContent='每列为一个节点，圆点大小表示该行指标的相对大小，颜色区分指标；悬停同一节点联动，综合评分加外圈。缺失值不绘制。\n点半径按该行指标的最小最大值标准化后平方根缩放，原始数值见悬停信息。';
 return c;
}
function mixingInformation(){
 const nav=el('div','subtabs'),host=el('div');tabs(nav,['全域与所有街道',...D.admins.map(g=>g.name)],i=>{
  charts.forEach(c=>c.dispose());charts=[];host.replaceChildren();
  note('雷达图越外扩，该维越多样；选择街道后点击道路可展开道路及各节点。\n'+MFORM);
  const groups=i?[D.admins[i-1],...D.admins[i-1].roads]:[D.all,...D.admins];const c=radar(host,groups,i?D.admins[i-1].name:'全域与所有街道');
  if(!i){const button=el('button','',host);button.textContent='信息散点图';const detail=el('section','drill',host);button.onclick=()=>{while(charts.length>1)charts.pop().dispose();detail.replaceChildren();el('h2','section-heading',detail).textContent='混合度信息散点图';el('p','caption',detail).textContent=MFORM;informationExplorer(detail,'mix');detail.scrollIntoView({behavior:'smooth',block:'start'})};return;}
  const admin=D.admins[i-1],buttons=el('div','road-buttons',host),drill=el('section','drill',host);
  function open(road){while(charts.length>1)charts.pop().dispose();drill.replaceChildren();el('h2','section-heading',drill).textContent=road;const group=admin.roads.find(g=>g.name===road),pts=D.points.filter(p=>p.admin===admin.name&&p.road===road&&p.n),grid=el('div','chart-grid',drill);radar(el('div','',grid),[group,...pts],road+'及各点位',480);lorenz(el('div','',grid),group);scorePlot(el('div','',grid),pts,'mixScore','点位混合度综合评分');el('p','caption',drill).textContent=MFORM;drill.scrollIntoView({behavior:'smooth',block:'start'})}
  admin.roads.forEach(g=>{const b=el('button','',buttons);b.textContent=g.name;b.onclick=()=>open(g.name)});c.on('legendselectchanged',p=>{if(admin.roads.some(g=>g.name===p.name)){c.dispatchAction({type:'legendSelect',name:p.name});open(p.name)}});c.on('click',p=>{if(admin.roads.some(g=>g.name===p.name))open(p.name)});
 });
}
function covarianceMatrix(){
 note('颜色由蓝到玫红表示负相关到正相关，近零为浅色。悬停格子时显示指标名称、系数、显著性和有效样本数。\nρ=两变量平均秩的Pearson相关系数；逐对排除缺失，并列值取平均秩。\nB1编码：无退让a=0、局部c=1、区域b=2、整体d=3；B2可视度a/b/c/d=0/1/2/3。\nB3a、b、c分别为对应构件子类出现数量；C尺度层级按C1至C4编码1至4。\n附属设施加权指数采用当前源表已计算的加权指数；未记录保留缺失。\n* p<0.05，** p<0.01，*** p<0.001，双侧近似检验，未做多重校正。');
 const wrap=el('div','covariance'),ys=Object.keys(D.ys),rows=D.fields.length,cols=ys.length;wrap.style.setProperty('--cols',cols);wrap.style.setProperty('--rows',rows);
 const grid=el('div','covariance-grid',wrap),hover=el('div','covariance-focus',wrap),rowbar=el('div','cov-row',hover),colbar=el('div','cov-col',hover),rowlabel=el('span','cov-row-label',hover),collabel=el('span','cov-col-label',hover),detail=el('div','cov-detail',wrap);hover.hidden=true;detail.hidden=true;
 function color(value){if(!finite(value))return '#F3EEE8';if(value>0){const a=value<.2?[243,238,232]:[213,155,168],b=value<.2?[213,155,168]:[164,86,104],t=value<.2?value/.2:Math.min(1,(value-.2)/.3);return 'rgb('+a.map((v,i)=>Math.round(v+(b[i]-v)*t)).join(',')+')';}const stops=['#607E95','#A8C3D6','#B8AEA6','#F3EEE8','#E2D0BC','#D59BA8','#A45668'],n=(value+1)*3,i=Math.min(5,Math.floor(n)),f=n-i,hex=h=>[1,3,5].map(k=>parseInt(h.slice(k,k+2),16)),a=hex(stops[i]),b=hex(stops[i+1]);return `rgb(${a.map((v,k)=>Math.round(v+(b[k]-v)*f)).join(',')})`}
 D.fields.forEach((field,y)=>ys.forEach((key,x)=>{const r=D.correlations.find(r=>r.x===field.key&&r.y===key),cell=el('button','cov-cell',grid);cell.style.background=color(r.rho);cell.setAttribute('aria-label',field.label+' / '+D.ys[key]+' '+fmt(r.rho));
  const activate=()=>{wrap.classList.add('has-focus');grid.querySelectorAll('button').forEach(b=>b.classList.toggle('chosen',b===cell));hover.hidden=false;detail.hidden=false;rowbar.style.top=(y/rows*100)+'%';rowbar.style.height=(100/rows)+'%';colbar.style.left=(x/cols*100)+'%';colbar.style.width=(100/cols)+'%';rowlabel.textContent=field.label;rowlabel.style.top=(y/rows*100)+'%';rowlabel.style.height=(100/rows)+'%';rowlabel.style.left=x>cols/2?'1%':'auto';rowlabel.style.right=x>cols/2?'auto':'1%';collabel.textContent=D.ys[key];collabel.style.left=((x+.5)/cols*100)+'%';collabel.style.top=y>rows/2?'2%':'auto';collabel.style.bottom=y>rows/2?'auto':'2%';detail.textContent=`ρ=${fmt(r.rho)}${stars(r.p)} · p=${finite(r.p)?r.p.toPrecision(3):'—'} · n=${r.n}`;};
  cell.addEventListener('pointerenter',activate);cell.addEventListener('focus',activate);
 }));const clear=()=>{wrap.classList.remove('has-focus');hover.hidden=true;detail.hidden=true;grid.querySelectorAll('button').forEach(b=>b.classList.remove('chosen'))};wrap.addEventListener('pointerleave',clear);wrap.addEventListener('focusout',e=>{if(!wrap.contains(e.relatedTarget))clear()});
 el('p','caption').textContent='负相关 −1　'+ '　—　接近0　—　'+'　正相关 +1';
}
function correlations(i){document.body.classList.remove('screen-analysis');if(i===0){covarianceMatrix();return;}if(i===1){note('每列代表一个节点，每行是一个指标；悬停显示同节点的全部信息并圈出综合评分。居民/游客指数用于对照展示，不纳入活动强度评分，以免把身份倾向当作活力高低。\n'+SFORM);vitalityInformation();return;}mixingInformation();}
function qualityChart(kind){const selected=D.qualityFields,desc=selected.map(k=>D.headers[k]).join('、');
 note('每个点为一个节点；横轴是从显著正相关空间指标构建的界面品质，纵轴为'+(kind==='qualityMix'?'混合度':'活力度')+'。\n指标筛选：'+(D.qualityRule||'ρ≥0.5 且 p<0.05')+'，相同空间指标只计一次。\nQ=(Σ z_j)/m，z_j=(x_j−min x_j)/(max x_j−min x_j)，m为筛出的空间指标数；任一输入缺失则Q缺失。\n本次入选：'+(desc||'无符合项，无法计算界面品质')+'。');
 if(!selected.length){el('p','empty').textContent='当前没有符合筛选标准的空间指标，界面品质暂无可计算结果。';return;}
 const key=kind==='qualityMix'?'mixScore':'vitality',c=chart(W,570),o=base();delete o.legend;o.xAxis={...axis('界面品质 Q'),min:0,max:1};o.yAxis={...axis(kind==='qualityMix'?'混合度 M':'活力度 V'),min:0,max:1};const pts=D.points.filter(p=>finite(p.quality)&&finite(p[key]));o.series=[{type:'scatter',data:pts.map(p=>[p.quality,p[key],p.address]),symbolSize:9,itemStyle:{color:PALETTE[0],opacity:.65}}];o.tooltip.formatter=p=>esc(p.data[2])+'<br>Q='+fmt(p.data[0])+'<br>评分='+fmt(p.data[1]);const f=fittedRegression(o.series[0].data);
 const controls=el('label','band-controls'),slider=el('input','',controls),value=el('span','',controls);slider.type='range';slider.min='0';slider.max='4';slider.step='0.05';slider.value='1.96';slider.setAttribute('aria-label','回归条带宽度');
 function update(){const k=Number(slider.value);value.textContent='回归条带宽度：'+k.toFixed(2)+' × 标准误';c.setOption({series:[o.series[0],...regressionSeries(f,Math.max(.000001,k),true)]},{replaceMerge:'series'});}
 c.setOption(o);update();slider.oninput=update;slider.disabled=!f;
 el('p','caption').textContent=(f?'OLS：y='+fmt(f.slope)+'x + '+fmt(f.intercept)+'；R²='+fmt(f.r2)+'；n='+f.n:'有效点不足或横轴恒定，无法拟合回归。')+'\n条带=拟合均值 ± k×SE，SE=s√[1/n+(x−x̄)²/Σ(xᵢ−x̄)²]，s=√[Σ(yᵢ−ŷᵢ)²/(n−2)]。滑条只调整k；这是可调标准误条带，不是固定置信水平。';
}
function mismatch(i){document.body.classList.add('screen-analysis');if(!i){note('越右越活跃，越上越多样；0.5划分高低，悬停查看节点。\n'+SFORM+'\n'+MFORM+'\nU=ln[(1+V)/(1+M)]；V=M时为0，V>M为正，V<M为负。');const c=chart(W,500),o=base();delete o.legend;o.grid={left:60,right:25,top:28,bottom:55,containLabel:true};o.xAxis={...axis('活力度 V'),min:0,max:1};o.yAxis={...axis('混合度 M'),min:0,max:1};const pts=D.points.filter(p=>finite(p.vitality)&&finite(p.mixScore));o.series=[{type:'scatter',id:'nodes',data:pts.map(p=>[p.vitality,p.mixScore,p.address,p.id]),symbolSize:8,itemStyle:{color:PALETTE[0],opacity:.6},markArea:{silent:true,itemStyle:{color:'rgba(164,86,104,0.14)'},label:{show:false},data:[[{xAxis:0.5,yAxis:0},{xAxis:1,yAxis:0.5}]]},markLine:{symbol:'none',silent:true,lineStyle:{color:'#B8AEA6',type:'dashed'},label:{show:false},data:[{xAxis:.5},{yAxis:.5}]}}];o.tooltip.formatter=p=>esc(p.data[2])+'<br>V='+fmt(p.data[0])+' / M='+fmt(p.data[1]);c.setOption(o);linkedNodeCharts();return;}
 note('仅显示高活力低混合节点。每个点对应一个节点，悬停查看名称和指标数值。\nU=ln[(1+V)/(1+M)]，横轴越大说明活力度相对混合度越高。\n附属设施加权指数及其余纵轴指标直接采用当前总表。\nOLS线性回归：R²≥0.5为深粉色实线，其余为浅粉色虚线；横轴恒定或有效点少于3不拟合。');
 const groups=[['有效空间',['K','L','M','S']],['功能',['O','P']],['界面基本品质',['T','U','V','W']],['界面舒适度',['Y','Z','AE','AF']],['配套设施品质',['AA','facility']]],nav=el('div','subtabs'),host=el('div','mismatch-panels');tabs(nav,groups.map(v=>v[0]),j=>{charts.forEach(c=>c.dispose());charts=[];host.replaceChildren();const grid=el('div','fixed-grid',host);groups[j][1].forEach(key=>{const c=chart(grid,300),o=base();delete o.legend;o.title={text:D.headers[key],left:'center',top:3,textStyle:{fontFamily:FONT,fontSize:14}};o.grid={left:60,right:20,top:45,bottom:50,containLabel:true};o.xAxis=axis('不配得性 U');o.xAxis.nameGap=25;o.yAxis=axis();const pts=D.points.filter(p=>p.quadrant==='高活力低混合'&&finite(p.values[key]));o.series=[{id:'nodes',type:'scatter',symbolSize:7,data:pts.map(p=>[p.mismatch,p.values[key],p.address,p.id]),itemStyle:{color:'#607E95',opacity:.65}}];o.tooltip.formatter=p=>esc(p.data[2])+'<br>U='+fmt(p.data[0])+'<br>'+esc(D.headers[key])+'：'+fmt(p.data[1]);const f=fittedRegression(o.series[0].data);o.series.push(...regressionSeries(f));o.graphic=[{type:'text',right:22,bottom:5,style:{text:f?'R²='+fmt(f.r2)+' · n='+f.n:'无法拟合（缺失或恒定）',font:'11px '+FONT,fill:'#4B4B4B'}}];c.setOption(o);});linkedNodeCharts();requestAnimationFrame(()=>charts.forEach(c=>c.resize()));});}





function vitalityInformation(){informationExplorer(W,'vitality');}
function informationExplorer(parent,kind){
 const mix=kind==='mix',keys=mix?['ageMix','activityMix','identityMix','postureMix','socialMix']:['sample','clusters','density','gather','resident','visitor'];
 const labels=[...keys.map(k=>D.ys[k]),'综合评分'],count=labels.length,last=count-1;
 const nav=el('div','subtabs',parent),host=el('div','',parent),c=informationScatter(host,kind),original=c.getOption();
 const controls=el('div','metric-controls',host),caption=host.querySelector('.caption');
 const values=keys.map(k=>D.points.map(p=>p.metrics[k]));values.push(D.points.map(p=>p[mix?'mixScore':'vitality']));
 const fits=values.map(v=>fittedRegression(v.map((y,x)=>[x,y]))),state=labels.map(()=>({visible:true,line:false,band:false}));let mode=0,selected=-1,phase=0,timer=null,generation=0;
 function cancelReveal(){generation++;if(timer!==null)clearTimeout(timer);timer=null;}
 function reveal(j){const f=fits[j];if(!f)return;const token=generation;let frame=0;
  function tick(){if(token!==generation||c.isDisposed())return;frame++;const lineProgress=Math.min(1,frame/30),bandProgress=Math.max(0,Math.min(1,(frame-30)/20));
   const end=(f.points.length-1)*lineProgress,k=Math.floor(end),points=f.points.slice(0,k+1).map(p=>p.slice(0,2));if(k<f.points.length-1){const a=f.points[k],b=f.points[k+1],t=end-k;points.push([a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t]);}
   c.setOption({series:[{id:'info-line-'+j,animation:false,data:points},{id:'info-band-'+j,animation:false,data:bandProgress>0?[0]:[],renderItem:(params,api)=>({type:'polygon',shape:{points:[...f.points.map(p=>api.coord([p[0],p[1]+1.96*p[2]*bandProgress])),...f.points.slice().reverse().map(p=>api.coord([p[0],p[1]-1.96*p[2]*bandProgress]))]},style:{fill:PALETTE[j],opacity:.14}})}]});
   if(frame<50)timer=setTimeout(tick,30);else timer=null;
  }timer=setTimeout(tick,30);
 }
 c.off('mouseover');c.off('globalout');
 labels.forEach((label,j)=>{const card=el('div','metric-control',controls);card.style.borderTopColor=PALETTE[j];
  const main=el('button','metric-toggle',card);main.textContent=label;main.setAttribute('aria-pressed','false');main.onclick=()=>{cancelReveal();phase=selected===j?(phase+1)%3:1;selected=phase?j:-1;state.forEach((s,k)=>{s.visible=selected<0||k===selected;s.line=false;s.band=false;});controls.querySelectorAll('button').forEach((b,k)=>b.setAttribute('aria-pressed',String(k===selected)));render();if(phase===1)reveal(j);};
 });
 function render(){const compact=window.innerWidth<700,step=compact?23:42,leftCount=Math.ceil(count/2);
  const axes=mode?labels.map((label,j)=>{const valid=values[j].filter(finite);return {id:'metric-'+j,type:'value',min:valid.length?Math.min(...valid):0,max:valid.length?Math.max(...valid):1,show:state[j].visible,position:j<leftCount?'left':'right',offset:(j<leftCount?j:j-leftCount)*step,name:String(j+1),nameLocation:'end',nameTextStyle:{color:PALETTE[j],fontFamily:FONT},axisLine:{show:true,lineStyle:{color:PALETTE[j]}},axisLabel:{fontSize:compact?8:10,color:'#4B4B4B',formatter:v=>Number(v.toPrecision(3)).toString()},splitLine:{show:false}}}):original.yAxis;
  const series=labels.map((name,j)=>({id:'info-'+j,type:'scatter',name,yAxisIndex:mode?j:0,data:values[j].map((v,k)=>({id:String(D.points[k].id),value:[k,mode?v:j,v]})),symbolSize:v=>!finite(v[2])||mode&&!state[j].visible?0:mode?(j===last?10:7):original.series[j].symbolSize(v),itemStyle:{color:PALETTE[j],opacity:.5},emphasis:{scale:1.5,itemStyle:{opacity:1}}}));
  labels.forEach((_,j)=>{const f=fits[j],enabled=mode&&state[j].visible,fit=regressionSeries(f,1.96,true);
   series.push({...fit[0],id:'info-line-'+j,type:'line',silent:true,yAxisIndex:mode?j:0,data:enabled&&state[j].line&&f?fit[0].data:[],lineStyle:{color:PALETTE[j],width:2,type:f&&f.r2>=.5?'solid':'dashed'}});
   series.push({...fit[1],id:'info-band-'+j,type:'custom',silent:true,clip:true,yAxisIndex:mode?j:0,data:enabled&&state[j].band&&f?[0]:[],renderItem:f?(params,api)=>({type:'polygon',shape:{points:[...f.points.map(p=>api.coord([p[0],p[1]+1.96*p[2]])),...f.points.slice().reverse().map(p=>api.coord([p[0],p[1]-1.96*p[2]]))]},style:{fill:PALETTE[j],opacity:.14}}):()=>null});
  });
  series.push({id:'focus-ring',type:'scatter',silent:true,yAxisIndex:mode?last:0,data:[],symbolSize:27,itemStyle:{color:'transparent',borderColor:PALETTE[last],borderWidth:2,opacity:1},z:10});
  c.setOption({animation:true,animationDurationUpdate:850,animationEasingUpdate:'cubicInOut',grid:{left:mode?step*(leftCount-1)+42:150,right:mode?step*(count-leftCount-1)+42:25,top:40,bottom:50},xAxis:mode?{type:'value',min:0,max:D.points.length-1,data:[],axisLabel:{show:false},axisTick:{show:false},name:'所有点位（按总表顺序）'}:original.xAxis,yAxis:axes,series},{replaceMerge:'yAxis'});
  controls.hidden=!mode;
  const text=(mode?count+'组散点叠加，各自独立纵轴从小到大；轴号依次对应：'+labels.join('、')+'。同一指标按钮依次点击：单项散点与回归动画 → 仅单项散点 → 全部指标。换点其他指标从第一步开始。不同指标的绝对高度不可直接比较。':'每列为一个点位，每行代表一个指标，点大小表示该行相对大小。')+'\n悬停联动同一点位，综合评分加外圈；切换视图时点位平滑移动。\n'+(mix?MFORM:SFORM);
  if(parent===W)note(text);else caption.textContent=text;
  if(parent===W)caption.textContent='回归横轴为总表点位顺序，不代表时间或空间距离。OLS：ŷ=a+bx，b=Σ[(x−x̄)(y−ȳ)]/Σ(x−x̄)²，a=ȳ−bx̄。\n条带=ŷ±1.96×s√[1/n+(x−x̄)²/Σ(x−x̄)²]，s²=Σ(y−ŷ)²/(n−2)。R²≥0.5实线，其余虚线；不将顺序趋势解释为因果。';
 }
 tabs(nav,['校准展示','散点图'],i=>{cancelReveal();selected=-1;phase=0;state.forEach(s=>{s.visible=true;s.line=false;s.band=false;});controls.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed','false'));mode=i;render();});
 if(parent!==W)el('p','caption',host).textContent='OLS以总表点位顺序为横轴：ŷ=a+bx，b=Σ[(x−x̄)(y−ȳ)]/Σ(x−x̄)²，a=ȳ−bx̄。条带=ŷ±1.96×SE，SE=s√[1/n+(x−x̄)²/Σ(x−x̄)²]，s²=Σ(y−ŷ)²/(n−2)。顺序趋势不表示时间、距离或因果。';
 c.setOption({tooltip:{formatter:p=>{const i=(p.data.value||p.data)[0],node=D.points[i];return node?esc(node.address)+'<br>'+labels.filter((_,j)=>!mode||state[j].visible).map(name=>{const j=labels.indexOf(name);return esc(name)+'：'+fmt(values[j][i])}).join('<br>'):''}}});
 c.on('mouseover',p=>{if(p.seriesIndex>=count)return;const i=(p.data.value||p.data)[0];c.dispatchAction({type:'downplay'});labels.forEach((_,j)=>{if(!mode||state[j].visible)c.dispatchAction({type:'highlight',seriesId:'info-'+j,dataIndex:i});});c.setOption({series:[{id:'focus-ring',data:finite(values[last][i])&&(!mode||state[last].visible)?[[i,mode?values[last][i]:last]]:[]}]});});
 c.on('globalout',()=>{c.dispatchAction({type:'downplay'});c.setOption({series:[{id:'focus-ring',data:[]}]});});
}
function scatter(parent,xkey,ykey,title){
 const c=chart(parent),o=base(),series=[],all=[];delete o.legend;o.title={text:title,left:'center',textStyle:{fontFamily:FONT,fontSize:16,color:INK}};o.xAxis=axis(D.headers[xkey]);o.yAxis=axis(D.headers[ykey]);
 [...new Set(D.points.map(p=>p.road))].forEach((road,j)=>{const data=D.points.filter(p=>p.road===road&&finite(p.values[xkey])&&finite(p.values[ykey])).map(p=>[p.values[xkey],p.values[ykey],p.address]);all.push(...data);
  if(data.length)series.push({id:'road-points-'+j,name:road,type:'scatter',data,symbolSize:8,itemStyle:{color:'#A8C3D6',opacity:.65},emphasis:{itemStyle:{color:'#607E95',opacity:1},scale:1.4}});
  const f=fittedRegression(data);if(f)series.push({id:'road-fit-'+j,name:road,type:'line',data:f.points.map(p=>p.slice(0,2)),showSymbol:false,silent:true,lineStyle:{color:'#929292',width:1,opacity:.4,type:f.r2>=.5?'solid':'dashed'},emphasis:{lineStyle:{color:'#666666',opacity:1,width:2.5}}});
 });
 const f=fittedRegression(all);if(f){series.push(...regressionSeries(f));o.graphic=[{type:'text',right:18,bottom:8,style:{text:`y=${fmt(f.slope)}x+${fmt(f.intercept)}\nR²=${fmt(f.r2)} · n=${f.n}`,fill:'#4B4B4B',font:'12px SimSun',lineHeight:17,textAlign:'right'}}];}
 o.series=series;o.tooltip.formatter=p=>p.seriesType==='scatter'?`${esc(p.data[2])}<br>${esc(D.headers[xkey])}：${fmt(p.data[0])}<br>${esc(D.headers[ykey])}：${fmt(p.data[1])}`:'';c.setOption(o);c.on('mouseover',p=>{if(p.seriesType==='scatter')highlight(p.seriesName)});c.on('globalout',()=>highlight(null));
}

if(PAGE==='heat')mainTabs(['样本数','热力分布'],mapView);
if(PAGE==='weights')weights();
if(PAGE==='composition')mainTabs(['街道年龄构成','点位年龄构成','身份倾向'],composition);
if(PAGE==='memory')mainTabs(D.memory.map(g=>g.cohort+'群体'),memory);
if(PAGE==='space')mainTabs(['有效空间分析','舒适度分析'],space);
if(PAGE==='diversity')mainTabs(['全域与所有街道',...D.admins.map(g=>g.name)],diversity);
if(PAGE==='correlations')mainTabs(['Spearman相关系数','活力度信息表','混合度信息表'],correlations);
if(PAGE==='qualityVitality'||PAGE==='qualityMix')qualityChart(PAGE);
if(PAGE==='mismatch')mainTabs(['筛选','不配得性分析'],mismatch);
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>charts.forEach(c=>{c.resize();c.reflow?.()}),120)});
'''

if __name__=='__main__':
    from _export import export_chart
    export_chart()
