"""街道人群构成：修改 JAVASCRIPT 后运行，即更新网站和发布包。"""
JAVASCRIPT = r'''/* Stable light-theme charts. All calculated values come from the shared point-ID dataset. */
'use strict';
const D=window.INCLUSIVE, PAGE=document.body.dataset.page;
const W=document.querySelector('.workspace'),NAV=document.querySelector('.tabs'),NOTE=document.querySelector('.readme');
const FONT='Times New Roman, SimSun, Songti SC, serif', INK='#292929', PALETTE=['#A4A6A7','#C6B8A7','#FCB45E','#292929','#4B4B4B'];
let charts=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const finite=Number.isFinite, fmt=(v,n=3)=>finite(v)?v.toFixed(n):'—';
const sum=a=>a.reduce((s,v)=>s+(finite(v)?v:0),0),mean=a=>{a=a.filter(finite);return a.length?sum(a)/a.length:null;};
const stars=p=>!finite(p)?'':p<.001?'***':p<.01?'**':p<.05?'*':'';
const SFORM='标准化值 z=(x−全域最小值)/(全域最大值−全域最小值)，常量指标记0。\n停留密度=行人样本数/有效停留空间面积。\n集聚比例=集聚人数/行人样本数。\n活力度 V=(z人数+z行为集群数+z停留密度+z集聚比例)/4；任一指标缺失则不评分。';
const MFORM='第 d 维混合度 H_d=−Σ(p_k×ln p_k)/ln K_d，p_k=该类别频数/该维频数合计，0×ln0记0。\n五维类别数依次为：年龄4、活动14、身份倾向2、姿态2、社交状态2。\n混合度综合评分 M=(H年龄+H活动+H身份倾向+H姿态+H社交状态)/5；任一维缺失则不评分。\n居民指数>游客指数记居民倾向，反之记游客倾向，相等或缺失不计入身份维；活动可多选。';
document.querySelector('.meta').textContent=`2026人因空间·${['composition','memory','diversity'].includes(PAGE)?D.recordCount:D.rows}RECORDS`;
function el(tag,cls,parent=W){const n=document.createElement(tag);if(cls)n.className=cls;parent.append(n);return n;}
function reset(){charts.forEach(c=>c.dispose());charts=[];W.replaceChildren();document.querySelector('.map-tooltip')?.remove();}
function tabs(parent,labels,render){parent.replaceChildren();labels.forEach((s,i)=>{const b=el('button','',parent);b.textContent=s;b.setAttribute('role','tab');b.onclick=()=>{parent.querySelectorAll('button').forEach(v=>v.setAttribute('aria-selected',String(v===b)));render(i);};if(!i)b.click();});}
function mainTabs(labels,render){tabs(NAV,labels,i=>{reset();render(i);});}
function note(text){NOTE.textContent=text;}
function chart(parent=W,height=520){const n=el('div','plot',parent);n.style.height=height+'px';const c=echarts.init(n,null,{renderer:'canvas'});charts.push(c);return c;}
function base(){return {animation:false,backgroundColor:'#fff',color:PALETTE,textStyle:{color:INK,fontFamily:FONT},title:{textStyle:{color:INK,fontFamily:FONT,fontSize:17,fontWeight:400}},tooltip:{confine:true,backgroundColor:'#fff',borderColor:'#A4A6A7',textStyle:{color:INK,fontFamily:FONT}},grid:{left:75,right:35,top:65,bottom:90,containLabel:true},legend:{top:38,left:20,right:20,type:'scroll',textStyle:{color:'#4B4B4B',fontFamily:FONT}},xAxis:axis(),yAxis:axis()};}
function axis(name=''){return {type:'value',name,nameLocation:'middle',nameGap:40,nameTextStyle:{color:'#4B4B4B',fontFamily:FONT},axisLabel:{color:'#4B4B4B',fontFamily:FONT},axisLine:{show:true,lineStyle:{color:'#A4A6A7'}},splitLine:{lineStyle:{color:'#C6B8A7'}}};}
function regression(a){if(a.length<2)return null;const mx=mean(a.map(p=>p[0])),my=mean(a.map(p=>p[1]));let xx=0,xy=0,yy=0;a.forEach(([x,y])=>{xx+=(x-mx)**2;xy+=(x-mx)*(y-my);yy+=(y-my)**2;});if(!xx)return null;return {b:xy/xx,a:my-xy/xx*mx,r2:yy?xy*xy/xx/yy:null,n:a.length,min:Math.min(...a.map(p=>p[0])),max:Math.max(...a.map(p=>p[0]))};}
function highlight(road){charts.forEach(c=>(c.getOption().series||[]).forEach((s,i)=>c.dispatchAction({type:s.name===road?'highlight':'downplay',seriesIndex:i})));}
function scatter(parent,xkey,ykey,title){const c=chart(parent),o=base(),series=[],all=[];delete o.legend;o.title={text:title,left:'center',textStyle:{fontFamily:FONT,fontSize:16,color:INK}};o.xAxis=axis(D.headers[xkey]);o.yAxis=axis(D.headers[ykey]);
 [...new Set(D.points.map(p=>p.road))].forEach(road=>{const data=D.points.filter(p=>p.road===road&&finite(p.values[xkey])&&finite(p.values[ykey])).map(p=>[p.values[xkey],p.values[ykey],p.address]);all.push(...data);if(data.length)series.push({name:road,type:'scatter',data,symbolSize:8,itemStyle:{color:'#A4A6A7',opacity:1},emphasis:{itemStyle:{color:'#292929'},scale:1.4}});});
 const f=regression(all);if(f){series.push({name:'回归线',type:'line',data:[[f.min,f.a+f.b*f.min],[f.max,f.a+f.b*f.max]],symbol:'none',silent:true,lineStyle:{color:'#292929',opacity:.18,type:f.r2>=.5?'solid':'dashed'}});o.graphic=[{type:'text',right:18,bottom:8,style:{text:`y=${fmt(f.b)}x+${fmt(f.a)}\nR²=${fmt(f.r2)} · n=${f.n}`,fill:'#4B4B4B',font:'12px SimSun',lineHeight:17,textAlign:'right'}}];}
 o.series=series;o.tooltip.formatter=p=>p.seriesType==='scatter'?`${esc(p.data[2])}<br>${esc(D.headers[xkey])}：${fmt(p.data[0])}<br>${esc(D.headers[ykey])}：${fmt(p.data[1])}`:'';c.setOption(o);c.on('mouseover',p=>{if(p.seriesType==='scatter')highlight(p.seriesName)});c.on('globalout',()=>highlight(null));}

function mapView(mode){note(mode===0?'选择活动查看原点位人数；圈越大人数越多，悬停时同一道路同时变实。\n圆半径 r=3+22×√(该点人数/当前指标最大人数)；按底图宽高的百分比定位。\n活动人数读取总表对应人数列；缺失观测仅在此地图按0显示。':'灰色表示人数少，橙色表示人数多；色块叠加展示人群在底图上的集中区域。\n权重 w=该点行人样本数/全域最大行人样本数。\n热度 h(x,y)=Σ[w_i×exp(−距离²/(2×σ²))]，σ=底图宽度的1.8%；热度按全图最大值归一化，缺失人数仅在此地图按0处理。');
 const tools=el('div','map-tools');let selected='AU';const pick=el('select','',tools);['AU','AV','AX','AY','BA','BB'].forEach(k=>{const option=el('option','',pick);option.value=k;option.textContent=D.headers[k]});if(mode===1)pick.hidden=true;
 const stage=el('div','map-stage'),img=el('img','',stage);img.src='../assets/data/map.jpg';img.alt='衡复风貌区调研底图';
 const NS='http://www.w3.org/2000/svg',svg=document.createElementNS(NS,'svg');svg.setAttribute('viewBox','0 0 1000 706.38');svg.setAttribute('role','img');svg.setAttribute('aria-label',mode?'行人样本数热力分布':'活动样本数地图');stage.append(svg);
 const tip=el('div','map-tooltip',document.body);tip.hidden=true;
 function hover(ev,p,key){tip.innerHTML=esc(p.address)+'<br>'+esc(D.headers[key])+'：'+fmt(p.values[key]??0,0);tip.hidden=false;tip.style.left=Math.min(ev.clientX+12,window.innerWidth-280)+'px';tip.style.top=Math.max(10,Math.min(ev.clientY+12,window.innerHeight-100))+'px';}
 function draw(){svg.replaceChildren();const key=mode?'AH':selected,max=Math.max(1,...D.points.map(p=>p.values[key]||0));
  if(mode){const canvas=document.createElement('canvas');canvas.width=700;canvas.height=495;const ctx=canvas.getContext('2d'),values=new Float32Array(700*495);let peak=0;const sigma=12.6;
   D.points.forEach(p=>{if(!p.position)return;const weight=Math.max(0,p.values.AH||0)/max,cx=p.position.x_percent*7,cy=p.position.y_percent*4.95;if(!weight)return;for(let y=Math.max(0,Math.floor(cy-3*sigma));y<Math.min(495,cy+3*sigma);y++)for(let x=Math.max(0,Math.floor(cx-3*sigma));x<Math.min(700,cx+3*sigma);x++){const v=values[y*700+x]+=weight*Math.exp(-((x-cx)**2+(y-cy)**2)/(2*sigma*sigma));peak=Math.max(peak,v);}});
   const pixels=ctx.createImageData(700,495),colors=[[164,166,167],[182,175,167],[198,184,167],[225,182,130],[252,180,94]];
   values.forEach((v,i)=>{if(!v)return;const t=v/peak,f=t*4,j=Math.min(3,Math.floor(f));for(let k=0;k<3;k++)pixels.data[i*4+k]=colors[j][k]*(1-(f-j))+colors[j+1][k]*(f-j);pixels.data[i*4+3]=255*Math.min(.82,t*5);});ctx.putImageData(pixels,0,0);const image=document.createElementNS(NS,'image');image.setAttribute('href',canvas.toDataURL());image.setAttribute('width','1000');image.setAttribute('height','706.38');svg.append(image);
  }
  D.points.forEach(p=>{if(!p.position)return;const n=p.values[key]||0,g=document.createElementNS(NS,'g');g.classList.add('map-point');g.dataset.road=p.road;g.setAttribute('tabindex','0');g.setAttribute('aria-label',p.address+' '+n+'人');g.setAttribute('transform',`translate(${p.position.x_percent*10},${p.position.y_percent*7.0638})`);
   const radius=mode?4:3+22*Math.sqrt(n/max);(mode?[1]:[1,.76,.5]).forEach((scale,i)=>{const c=document.createElementNS(NS,'circle');c.setAttribute('r',radius*scale);c.setAttribute('fill',mode?'#292929':'#FCB45E');c.setAttribute('fill-opacity',mode?'.04':n===0?'.04':String(.12+i*.08));c.setAttribute('stroke','#292929');c.setAttribute('stroke-opacity',mode?'0':'.13');g.append(c)});
   const activate=e=>{svg.querySelectorAll('.map-point').forEach(v=>v.classList.toggle('active',v.dataset.road===p.road));if(e.clientX!==undefined)hover(e,p,key);};g.addEventListener('pointerenter',activate);g.addEventListener('pointermove',e=>hover(e,p,key));g.addEventListener('focus',activate);const clear=()=>{svg.querySelectorAll('.active').forEach(v=>v.classList.remove('active'));tip.hidden=true};g.addEventListener('pointerleave',clear);g.addEventListener('blur',clear);svg.append(g);
  });
 }
 pick.onchange=()=>{selected=pick.value;draw()};draw();if(mode){const legend=el('div','heat-legend');legend.innerHTML='低人数 <span class="heat-gradient"></span> 高人数';}
}

function weights(){note('每行代表一条道路，六段长度表示各项评分均值；悬停查看评分及所占比例。\n道路某项均值=该道路有效评分之和/有效点位数。\n遮荫评分=遮荫率(%)/20。\n六项合计=开放度+互动性+视觉丰富度+历史感知度+遮荫评分+路面状态，满分30。\n某项构成比例=该项均值/六项均值合计×100%。');const c=chart(W,Math.max(650,D.weights.length*29+120)),o=base(),names=['界面开放度','临街互动性','视觉丰富度','历史感知度','遮荫率','路面状态'];o.grid={left:100,right:30,top:70,bottom:35};o.xAxis=axis();o.yAxis={type:'category',data:D.weights.map(g=>g.road),axisLabel:{fontFamily:FONT,interval:0},inverse:true};o.series=names.map((name,j)=>({name,type:'bar',stack:'total',data:D.weights.map(g=>g.values[j]),itemStyle:{color:['#292929','#4B4B4B','#A4A6A7','#C6B8A7','#FCB45E','#A4A6A7'][j],opacity:j===5?.55:1},label:{show:true,color:j<2?'#fff':'#292929',formatter:p=>fmt(p.value,1)}}));o.tooltip.trigger='axis';o.tooltip.formatter=ps=>esc(ps[0].name)+'<br>'+ps.map(p=>`${esc(p.seriesName)}：${fmt(p.value,2)} (${fmt(p.value/sum(ps.map(v=>v.value))*100,1)}%)`).join('<br>');c.setOption(o);}
function composition(i){const age=i!==2,key=age?'ages':'identities',labels=age?['幼年','青年','中年','老年']:['居民倾向','游客倾向'];let groups=i===1?D.points.filter(p=>p.n).slice().sort((a,b)=>b.ages[3]/sum(b.ages)-a.ages[3]/sum(a.ages)):[D.all,...D.admins.slice().sort((a,b)=>b[key][age?1:0]/sum(b[key])-a[key][age?1:0]/sum(a[key]))];note('每行总长为该群体的有效构成，悬停查看人数；点位年龄构成按老年比例排序。\n类别比例=该类人数/该维有效人数×100%。\n居民指数>游客指数记居民倾向，反之记游客倾向；相等或缺失不计入身份构成。');const c=chart(W,Math.max(490,groups.length*28+120)),o=base();o.grid={left:i===1?240:140,right:35,top:70,bottom:40};o.xAxis={...axis('构成（%）'),max:100};o.yAxis={type:'category',data:groups.map(g=>g.name+' · n='+g.n),inverse:true,axisLabel:{interval:0,fontSize:11,fontFamily:FONT}};o.series=labels.map((name,j)=>({name,type:'bar',stack:'share',data:groups.map(g=>sum(g[key])?g[key][j]/sum(g[key])*100:null),itemStyle:{color:['#292929','#A4A6A7','#C6B8A7','#FCB45E'][j],opacity:!age&&j===1?.35:1},label:{show:true,color:j===0?'#fff':'#292929',formatter:p=>p.value>=8?fmt(p.value,1)+'%':''}}));o.tooltip.trigger='axis';c.setOption(o);}
function memory(i){note('连线宽度表示该年龄群体的观测条数；左侧是活动推演的原初功能，右侧是点位当前功能。\n映射按饮食→餐饮/饮品、光顾→零售、工作→生产/办公、打卡→文化展示优先匹配，其余归为生活服务。\n每条记录只进入一个映射，连线人数=对应映射的记录条数。\n这是代际偏好假设，非历史用途实测，也不把年龄层直接换算为具体年份。');const g=D.memory[i],c=chart(W,Math.max(550,Math.min(850,window.innerHeight*.8))),o=base();delete o.xAxis;delete o.yAxis;delete o.grid;delete o.legend;const left=[...new Set(g.links.map(v=>v.source))],right=[...new Set(g.links.map(v=>v.target))];
 const layout=()=>{const narrow=c.getWidth()<650;return {series:[{type:'sankey',left:narrow?8:'19%',right:narrow?8:'23%',top:35,bottom:25,nodeWidth:12,nodeGap:16,draggable:false,data:[...left.map(name=>({name:'假设：'+name,depth:0})),...right.map(name=>({name:'当前：'+name,depth:1}))],links:g.links.map(v=>({source:'假设：'+v.source,target:'当前：'+v.target,value:v.value})),itemStyle:{color:'#292929',borderWidth:0},lineStyle:{color:'#292929',opacity:.16},label:{color:'#292929',fontFamily:FONT,fontSize:narrow?10:12,width:narrow?120:180,overflow:'break',formatter:p=>p.name.replace(/^(假设：|当前：)/,'')},levels:[{depth:0,label:{position:narrow?'right':'left'}},{depth:1,label:{position:narrow?'left':'right'}}],emphasis:{focus:'adjacency',lineStyle:{opacity:.5}}}]};};o.tooltip.formatter=p=>p.dataType==='edge'?`${esc(p.data.source)} → ${esc(p.data.target)}<br>${p.data.value}条观测`:esc(p.name);c.setOption({...o,...layout()});c.reflow=()=>c.setOption(layout());}
function space(i){note('每个点代表一个节点，悬停同步突出同一道路；线表示整体趋势，实线 R²≥0.5，虚线 R²<0.5。右下角显示回归方程、R²和有效点位数。\n斜率 b=Σ[(x−x̄)(y−ȳ)]/Σ(x−x̄)²。\n截距 a=ȳ−b×x̄，预测值 ŷ=a+bx。\nR²=1−Σ(y−ŷ)²/Σ(y−ȳ)²；分母为0时不定义，缺失值逐对排除。\n节点空间长度、有效面积、承载人数、消费空间占比及各舒适度指标直接采用总表记录。');if(i===0){const sub=el('div','subtabs'),host=el('div','single-space-chart');const options=[['M','空间有效性分析'],['S','空间承载力分析'],['R','消费空间占比分析']];tabs(sub,options.map(v=>v[1]),j=>{charts.forEach(c=>c.dispose());charts=[];host.replaceChildren();scatter(host,'K',options[j][0],options[j][1]);});}else{const grid=el('div','chart-grid');[['AE','遮荫率'],['AF','声环境舒适度'],['AG','气味环境']].forEach(([y,t])=>scatter(grid,'T',y,t));}}

function radar(parent,groups,title,height=530){const c=chart(parent,height),o=base();delete o.xAxis;delete o.yAxis;delete o.grid;const dims=['年龄','活动','身份倾向','姿态','社交状态'];o.title={text:title,left:'center',top:0,textStyle:{fontSize:16,fontFamily:FONT}};o.legend.top=30;o.radar={center:['50%','57%'],radius:'59%',indicator:dims.map(name=>({name,max:1})),axisName:{color:'#292929',fontFamily:FONT},splitArea:{show:false},axisLine:{lineStyle:{color:'#C6B8A7'}},splitLine:{lineStyle:{color:'#C6B8A7'}}};o.series=groups.filter(g=>g.mix.every(finite)).map((g,j)=>({name:g.name,type:'radar',symbol:['circle','rect','triangle','diamond'][j%4],symbolSize:5,lineStyle:{color:PALETTE[j%5],opacity:j?.7:1,type:j?'solid':'dashed',width:j?1:2},itemStyle:{color:PALETTE[j%5]},data:[{name:g.name,value:g.mix}],emphasis:{lineStyle:{width:3,opacity:1}}}));o.tooltip.formatter=p=>esc(p.name)+'<br>'+dims.map((v,j)=>v+'：'+fmt(p.value[j])).join('<br>');c.setOption(o);return c;}
function scorePlot(parent,points,key,title){const compact=key==='mixScore',valid=points.filter(p=>finite(p[key])),container=el('div',compact?'score-wrap score-fit':'score-wrap',parent),c=chart(container,480),o=base();delete o.legend;o.title={text:title,left:'center',textStyle:{fontFamily:FONT,fontSize:16}};o.grid={left:60,right:24,top:80,bottom:compact?45:120,containLabel:true};o.xAxis={...axis(),type:'category',data:valid.map(p=>p.name),axisTick:{show:!compact},axisLabel:{show:!compact,rotate:45,interval:0,fontSize:10,fontFamily:FONT}};o.yAxis={...axis('综合评分'),min:0,max:1};o.series=[{type:'scatter',symbolSize:7,data:valid.map(p=>p[key]),itemStyle:{color:'#4B4B4B',opacity:1},label:{show:true,position:'top',color:'#292929',fontFamily:FONT,fontSize:10,formatter:p=>fmt(p.value,2)}}];o.tooltip.formatter=p=>esc(valid[p.dataIndex].address)+'<br>评分：'+fmt(p.value)+'<br>行人样本 n='+valid[p.dataIndex].n;c.setOption(o);return c;}
function lorenz(parent,g){const c=chart(parent,480),o=base(),order=g.actions.map((v,j)=>({v,j})).sort((a,b)=>a.v-b.v||a.j-b.j);o.title={text:'行为集中度：洛伦兹曲线',left:'center',top:5,textStyle:{fontFamily:FONT,fontSize:16}};o.legend={...o.legend,top:40,left:10,right:10};o.grid={left:55,right:20,top:92,bottom:115,containLabel:true};o.xAxis={...axis(),type:'category',data:['起点',...order.map(p=>D.behaviorLabels[p.j])],axisLabel:{rotate:55,interval:0,fontSize:10,fontFamily:FONT}};o.yAxis={...axis('行为出现次数累计比例'),min:0,max:1};o.series=[{name:'均等线',type:'line',data:Array.from({length:15},(_,i)=>i/14),symbol:'none',lineStyle:{color:'#A4A6A7',type:'dashed'}},{name:g.name,type:'line',data:g.lorenz||[],symbolSize:4,lineStyle:{color:'#292929'},itemStyle:{color:'#292929'}}];o.tooltip.trigger='axis';c.setOption(o);}
function diversity(i){note('五边形越外扩，群体在相应维度越多样；点击行政街道内的道路，向下查看该道路及点位、行为曲线和综合评分。小样本点位仍显示，但 n<5 的结果容易波动。\n'+MFORM+'\n洛伦兹纵坐标 L_j=前j类行为频数累计/14类行为频数合计，行为按频数从低到高排序。');const groups=i===0?[D.all,...D.admins]:[D.admins[i-1],...D.admins[i-1].roads];const c=radar(W,groups,i===0?'全域与所有街道':D.admins[i-1].name);if(!i)return;const admin=D.admins[i-1],buttons=el('div','road-buttons'),drill=el('section','drill');
 function open(road){while(charts.length>1){charts.pop().dispose()}drill.replaceChildren();el('h2','section-heading',drill).textContent=road+' · 道路与节点';const group=admin.roads.find(g=>g.name===road),pts=D.points.filter(p=>p.admin===admin.name&&p.road===road&&p.n);const grid=el('div','chart-grid',drill),a=el('div','',grid),b=el('div','',grid),d=el('div','',grid);radar(a,[group,...pts],road+'及各点位',480);lorenz(b,group);scorePlot(d,pts,'mixScore','点位混合度综合评分');el('p','caption',drill).textContent='点位标注为地址，悬停可查看样本量。\n'+MFORM;drill.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});}
 admin.roads.forEach(g=>{const b=el('button','',buttons);b.textContent=g.name;b.onclick=()=>open(g.name)});c.on('legendselectchanged',p=>{if(admin.roads.some(g=>g.name===p.name)){c.dispatchAction({type:'legendSelect',name:p.name});open(p.name)}});c.on('click',p=>{if(admin.roads.some(g=>g.name===p.name))open(p.name)});
}

function correlations(i){if(i===1){note('每个点显示一个节点的活力度评分，点上方标出分数；分数越高，当前观测下的活动强度越高。缺少评分输入的点位列在图后。\n'+SFORM);scorePlot(W,D.points,'vitality','活力度综合评分');missingScores('vitality');return;}
 note('圆越大，关联越强；实心表示正相关，空心表示负相关；数值下方显示星号显著性，—表示数据不足或指标不变化。\nρ=Σ[(R_x−R̄_x)(R_y−R̄_y)]/√[Σ(R_x−R̄_x)²×Σ(R_y−R̄_y)²]，并列值采用平均秩，逐对排除缺失。\nA、B1、B2、B3、C、D按具体类别展开：某类别出现=1，未出现=0；整项未记录保留缺失。\n'+SFORM+'\n年龄混合度 H=−Σ(p_k ln p_k)/ln4。\n居民/游客指数=该点位行人表相应指数的有效值均值。\n* p<0.05，** p<0.01，*** p<0.001；p为双侧Spearman近似检验，未做多重检验校正。');
 const ys=Object.keys(D.ys),wrap=el('div','table-scroll');let html='<table><thead><tr><th>空间指标 / 行人指标</th>'+ys.map(k=>'<th>'+esc(D.ys[k])+'</th>').join('')+'</tr></thead><tbody>';
 D.fields.forEach(f=>{html+='<tr><th>'+esc(f.label)+'</th>'+ys.map(y=>{const r=D.correlations.find(r=>r.x===f.key&&r.y===y);if(!finite(r.rho))return '<td title="有效配对 '+r.n+'">—</td>';const size=32+36*Math.sqrt(Math.abs(r.rho));return `<td class="circle-cell" title="n=${r.n}; p=${r.p}"><span class="circle ${r.rho<0?'negative':'positive'}" style="width:${size}px;height:${size}px;--alpha:${.5+.5*Math.abs(r.rho)}">${fmt(r.rho)}${stars(r.p)}</span></td>`}).join('')+'</tr>';});wrap.innerHTML=html+'</tbody></table>';
 const heading=el('h2','section-heading');heading.textContent='Spearman相关系数';const table=el('div','table-scroll');table.innerHTML='<table><thead><tr><th>空间指标 / 行人指标</th>'+ys.map(k=>'<th>'+esc(D.ys[k])+'</th>').join('')+'</tr></thead><tbody>'+D.fields.map(f=>'<tr><th>'+esc(f.label)+'</th>'+ys.map(y=>{const r=D.correlations.find(r=>r.x===f.key&&r.y===y);return '<td>'+fmt(r.rho)+stars(r.p)+'</td>'}).join('')+'</tr>').join('')+'</tbody></table>';
}
function missingScores(key){const pts=D.points.filter(p=>!finite(p[key]));if(pts.length){const p=el('p','notice');p.textContent=`${pts.length} 个点位缺少评分输入，未将缺失填为0：`+pts.map(p=>p.name).join('、');}}
function mismatch(i){if(!i){note('横轴活力度、纵轴混合度，越右越活跃、越上越多样；虚线以0.5划分高低，悬停查看节点。缺少任一评分的点位不绘制。\n'+SFORM+'\n'+MFORM+'\n高活力低混合：V≥0.5且M<0.5；双高：V≥0.5且M≥0.5。');const c=chart(W,600),o=base();o.xAxis={...axis('活力度 V'),min:0,max:1};o.yAxis={...axis('混合度 M'),min:0,max:1};const pts=D.points.filter(p=>finite(p.vitality)&&finite(p.mixScore));o.series=[{type:'scatter',symbolSize:9,data:pts.map(p=>[p.vitality,p.mixScore,p.address,p.n]),itemStyle:{color:'#4B4B4B',opacity:1},markLine:{silent:true,symbol:'none',lineStyle:{color:'#A4A6A7',type:'dashed'},label:{show:false},data:[{xAxis:.5},{yAxis:.5}]},markArea:{silent:true,itemStyle:{color:'#00000003'},label:{color:'#4B4B4B',fontFamily:FONT},data:[[{name:'低活力高混合',xAxis:0,yAxis:.5},{xAxis:.5,yAxis:1}],[{name:'双高',xAxis:.5,yAxis:.5},{xAxis:1,yAxis:1}],[{name:'双低',xAxis:0,yAxis:0},{xAxis:.5,yAxis:.5}],[{name:'高活力低混合',xAxis:.5,yAxis:0},{xAxis:1,yAxis:.5}]]}}];o.tooltip.formatter=p=>`${esc(p.data[2])}<br>V=${fmt(p.data[0])}，M=${fmt(p.data[1])}<br>行人样本 n=${p.data[3]}`;c.setOption(o);missingScores('mismatch');return;}
 note('两个板块分别比较高活力低混合和双高点位。选择界面指标，横轴是不配得性，纵轴是所选评分；按不配得性顺序连接观测点，连线仅帮助阅读，不代表时间变化或因果。\n不配得性 U=ln[(1+V)/(1+M)]；V=M时为0，V>M为正，V<M为负。\nV、M均为0–1评分；加入1使零值可计算，双高或双低且相近时U接近0。\n遮荫评分=遮荫率(%)/20；其余界面指标使用总表评分。');const sub=el('div','subtabs'),host=el('div');const keys=['U','V','Y','Z','AE','AA'];tabs(sub,keys.map(k=>k==='AE'?'遮荫评分':D.headers[k]),idx=>{charts.forEach(c=>c.dispose());charts=[];host.replaceChildren();const grid=el('div','chart-grid two',host);['高活力低混合','双高'].forEach(group=>{const panel=el('section','',grid);el('h2','section-heading',panel).textContent=group;const key=keys[idx],pts=D.points.filter(p=>p.quadrant===group&&finite(p.values[key])).sort((a,b)=>a.mismatch-b.mismatch);if(!pts.length){el('p','empty',panel).textContent='当前没有满足条件且该指标有效的点位。';return;}const c=chart(panel,490),o=base();o.xAxis=axis('不配得性 U');o.yAxis=axis(key==='AE'?'遮荫评分':D.headers[key]);o.series=[{type:'line',data:pts.map(p=>[p.mismatch,p.values[key]/(key==='AE'?20:1),p.address]),symbolSize:8,lineStyle:{color:'#4B4B4B',opacity:.4},itemStyle:{color:'#292929'},label:{show:true,position:'top',fontFamily:FONT,fontSize:10,formatter:p=>fmt(p.data[1],1)}}];o.tooltip.formatter=p=>esc(p.data[2])+'<br>U='+fmt(p.data[0])+'<br>评分='+fmt(p.data[1]);c.setOption(o);});});}

if(PAGE==='heat')mainTabs(['样本数','热力分布'],mapView);
if(PAGE==='weights')weights();
if(PAGE==='composition')mainTabs(['街道年龄构成','点位年龄构成','身份倾向'],composition);
if(PAGE==='memory')mainTabs(D.memory.map(g=>g.cohort+'群体'),memory);
if(PAGE==='space')mainTabs(['有效空间分析','舒适度分析'],space);
if(PAGE==='diversity')mainTabs(['全域与所有街道',...D.admins.map(g=>g.name)],diversity);
if(PAGE==='correlations')mainTabs(['Spearman相关系数','活力度综合评分'],correlations);
if(PAGE==='mismatch')mainTabs(['筛选','不配得性分析'],mismatch);
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>charts.forEach(c=>{c.resize();c.reflow?.()}),120)});
'''

if __name__=='__main__':
    from _export import export_chart
    export_chart()
