const fs=require('fs'),vm=require('vm'),assert=require('assert'),echarts=require('../spacemovement/echarts.min.js');
const PAGES=['heat','weights','composition','memory','space','correlations','qualityVitality','qualityMix','mismatch'];let rendered=0;
function setup(page,width=1100){
 const all=[],made=[],timers=new Map();let timerId=0;const queue=f=>{timers.set(++timerId,f);return timerId;};
 function element(tag='div'){const n={tag,children:[],style:{setProperty(k,v){this[k]=v}},dataset:{},attrs:{},listeners:{},className:'',textContent:'',innerHTML:'',hidden:false,
 append(c){this.children.push(c)},replaceChildren(){this.children=[];this.innerHTML=''},setAttribute(k,v){this.attrs[k]=String(v)},addEventListener(k,f){this.listeners[k]=f},scrollIntoView(){this.scrolled=true},remove(){},contains(c){return this.children.includes(c)},
 querySelectorAll(s){let found=[];for(const c of this.children){if((s==='button'&&c.tag==='button')||(s[0]==='.'&&c.className.split(' ').includes(s.slice(1))))found.push(c);found.push(...c.querySelectorAll(s));}return found},querySelector(s){return this.querySelectorAll(s)[0]||null},click(){this.onclick?.()},
 getContext(){return {createImageData(w,h){return {data:new Uint8ClampedArray(w*h*4)}},putImageData(){}}},toDataURL(){return 'data:image/png;base64,test'}};
 n.classList={add(s){n.className+=' '+s},remove(s){n.className=n.className.split(' ').filter(v=>v!==s).join(' ')},toggle(s,b){b?this.add(s):this.remove(s)}};all.push(n);return n;}
 const elements={};['.workspace','.tabs','.readme','.meta'].forEach(k=>elements[k]=element());const body=element('body');body.dataset.page=page;
 const context={console,setTimeout:queue,clearTimeout:id=>timers.delete(id),requestAnimationFrame:f=>f(),window:{innerWidth:width,innerHeight:900,addEventListener(){},matchMedia(){return {matches:true}}},document:{body,querySelector:s=>elements[s]||body.querySelector(s),createElement:element,createElementNS:(_,s)=>element(s)},echarts:{init(el){const c=echarts.init(null,null,{renderer:'svg',ssr:true,width,height:parseInt(el.style.height)||500});const resize=c.resize.bind(c);c.resize=()=>resize({width,height:parseInt(el.style.height)||500});made.push(c);return c;}}};
 vm.createContext(context);vm.runInContext(fs.readFileSync('docs/assets/data/inclusive-data.js','utf8'),context);vm.runInContext(fs.readFileSync('docs/assets/js/chart-'+String(PAGES.indexOf(page)+1).padStart(2,'0')+'.js','utf8'),context);
 return {all,made,elements,context,advance(n){for(let i=0;i<n&&timers.size;i++){const [id,f]=timers.entries().next().value;timers.delete(id);f();}},check(){for(const c of made.filter(c=>!c.isDisposed())){const svg=c.renderToSVGString();assert(!svg.includes('NaN'),page+' invalid SVG');assert.equal(c.getOption().backgroundColor,'#fff');fs.writeFileSync(`.site-build/revision-${page}-${width}.svg`,svg);rendered++;}},dispose(){made.filter(c=>!c.isDisposed()).forEach(c=>c.dispose())}};
}
for(const page of PAGES){const t=setup(page);t.check();
 if(page==='correlations'){
  assert.equal(t.elements['.tabs'].children.length,3);const grid=t.all.find(n=>n.className==='covariance-grid');assert.equal(grid.children.length,264);
  for(const i of [0,10,253,263]){grid.children[i].listeners.pointerenter();assert(t.all.find(n=>n.className==='cov-row-label').textContent);assert(t.all.find(n=>n.className==='cov-col-label').textContent);}
  t.elements['.tabs'].children[1].click();t.check();let c=t.made.filter(c=>!c.isDisposed())[0];assert.equal(c.getOption().yAxis[0].data.length,7);c.trigger('mouseover',{seriesIndex:0,data:[0,0,1]});assert(c.getOption().series.some(s=>s.id==='focus-ring'));c.trigger('globalout');
  t.elements['.tabs'].children[2].click();const sub=t.elements['.workspace'].children[0];const info=t.all.find(n=>n.textContent==='信息散点图');info.click();t.check();c=t.made.filter(c=>!c.isDisposed()).at(-1);assert.equal(c.getOption().yAxis[0].data.length,6);c.trigger('mouseover',{seriesIndex:1,data:[2,1,.2]});
  for(const b of sub.children.slice(1)){b.click();const roads=t.all.filter(n=>n.className==='road-buttons').at(-1);for(const road of roads.children){road.click();t.check();assert.equal(t.made.filter(c=>!c.isDisposed()).length,4);}}
 }else{for(const b of t.elements['.tabs'].children.slice(1)){b.click();t.check();}}
 if(page==='mismatch'){const sub=t.elements['.workspace'].children[0];assert.equal(sub.children.length,5);for(const b of sub.children){b.click();t.check();const active=t.made.filter(c=>!c.isDisposed());assert([2,4].includes(active.length));for(const c of active){const nodes=c.getOption().series.find(s=>s.id==='nodes');assert.equal(nodes.itemStyle.color,'#607E95');if(nodes.data.length){c.trigger('mouseover',{seriesId:'nodes',seriesIndex:0,data:nodes.data[0]});assert(c.getOption().series[0].emphasis.label.show);c.trigger('globalout');}const line=c.getOption().series.find(s=>s.id==='regression');if(line)assert(['#A45668','#D59BA8'].includes(line.lineStyle.color));}}}
 if(page==='qualityVitality'||page==='qualityMix'){const slider=t.all.find(n=>n.type==='range');assert(slider);const c=t.made.find(c=>!c.isDisposed());for(const value of ['0','1','4']){slider.value=value;slider.oninput();t.check();assert(c.getOption().series.some(s=>s.id==='regression-band'));}}
 t.dispose();}
for(const width of [375,768]){for(const p of ['memory','correlations','mismatch']){const t=setup(p,width);t.check();t.dispose();}}
console.log(`Checked 9 routes, 264-cell matrix hover, linked information scatters, every road drilldown, five mismatch categories and ${rendered} chart renderings.`);
for(const kind of ['vitality','mix']){const t=setup('correlations');t.elements['.tabs'].children[kind==='mix'?2:1].click();if(kind==='mix')t.all.find(n=>n.textContent==='信息散点图').click();const nav=t.all.filter(n=>n.className==='subtabs').at(-1);nav.children[1].click();const c=t.made.filter(c=>!c.isDisposed()).at(-1),cards=t.all.filter(n=>n.className==='metric-control');assert.equal(cards.length,kind==='mix'?6:7);const series=id=>c.getOption().series.find(s=>s.id===id);for(let j=0;j<cards.length;j++){assert.equal(cards[j].children.length,1);const main=cards[j].children[0];main.click();assert.equal(c.getOption().yAxis.filter(a=>a.show).length,1);t.advance(15);assert(series('info-line-'+j).data.length>0&&series('info-line-'+j).data.length<61);assert.equal(series('info-band-'+j).data.length,0);t.advance(15);assert.equal(series('info-line-'+j).data.length,61);assert.equal(series('info-band-'+j).data.length,0);t.advance(20);assert.equal(series('info-band-'+j).data.length,1);t.check();main.click();assert.equal(series('info-line-'+j).data.length,0);assert.equal(series('info-band-'+j).data.length,0);assert.equal(c.getOption().yAxis.filter(a=>a.show).length,1);main.click();assert.equal(c.getOption().yAxis.filter(a=>a.show).length,cards.length);}cards[0].children[0].click();t.advance(5);cards[1].children[0].click();t.advance(50);assert.equal(series('info-line-0').data.length,0);nav.children[0].click();t.advance(60);t.check();t.dispose();t.advance(60);}
{const t=setup('mismatch'),c=t.made[0],area=c.getOption().series[0].markArea;assert.equal(area.data[0][0].xAxis,.5);assert.equal(area.data[0][0].yAxis,0);assert.equal(area.data[0][1].xAxis,1);assert.equal(area.data[0][1].yAxis,.5);t.check();t.dispose();}
{const t=setup('space');for(const tab of t.elements['.tabs'].children){tab.click();for(const c of t.made.filter(c=>!c.isDisposed())){const series=c.getOption().series;assert(series.some(s=>String(s.id).startsWith('road-fit-')));const fit=series.find(s=>s.id==='regression');assert(fit&&['#D59BA8','#A45668'].includes(fit.lineStyle.color));const road=series.find(s=>s.type==='scatter');c.trigger('mouseover',{seriesType:'scatter',seriesName:road.name});c.trigger('globalout');}t.check();}t.dispose();}console.log('Verified all metric/line/band toggles in both explorers and road regression series.');
{const t=setup('correlations');t.elements['.tabs'].children[1].click();const sub=t.elements['.workspace'].children[0],c=t.made.find(c=>!c.isDisposed());assert.equal(sub.children.length,2);for(const i of [1,0,1,0]){sub.children[i].click();t.check();assert.equal(c.getOption().yAxis.length,i?7:1);assert.equal(c.getOption().animationDurationUpdate,850);c.trigger('mouseover',{seriesIndex:0,data:c.getOption().series[0].data[0]});c.trigger('globalout');}t.dispose();console.log('Verified animated vitality mode changes, regression bands at 3 widths, blue points and linked labels.');}



